### logout
GET {{host}}/auth/logout.json

### login-page
GET {{host}}/auth/login-page.json

### github login-page
GET {{host}}/auth/github/login-page.html

### github login-page
GET {{host}}/auth/github/login-page.json

### get root nonce
POST {{host}}/auth/console-nonce.json

### root nonce login
POST {{host}}/auth/username/login.json
Content-Type: application/x-www-form-urlencoded

username=root&password=88rE4TtheH72Df3Q
