/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.oracle.database.autogen;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pro.fessional.wings.oracle.database.autogen.tables.SysCommitJournal;
import pro.fessional.wings.oracle.database.autogen.tables.SysLightSequence;
import pro.fessional.wings.oracle.database.autogen.tables.SysSchemaManager;
import pro.fessional.wings.oracle.database.autogen.tables.SysSchemaVersion;
import pro.fessional.wings.oracle.service.lightid.LightIdAware;


/**
 * The schema <code>wings</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9",
        "schema version:2019051201"
    },
    date = "2019-06-03T13:01:45.550Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl implements LightIdAware {

    private static final long serialVersionUID = 482008014;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>SYS_COMMIT_JOURNAL</code>.
     */
    public final SysCommitJournal SYS_COMMIT_JOURNAL = pro.fessional.wings.oracle.database.autogen.tables.SysCommitJournal.SYS_COMMIT_JOURNAL;

    /**
     * The table <code>SYS_LIGHT_SEQUENCE</code>.
     */
    public final SysLightSequence SYS_LIGHT_SEQUENCE = pro.fessional.wings.oracle.database.autogen.tables.SysLightSequence.SYS_LIGHT_SEQUENCE;

    /**
     * The table <code>SYS_SCHEMA_MANAGER</code>.
     */
    public final SysSchemaManager SYS_SCHEMA_MANAGER = pro.fessional.wings.oracle.database.autogen.tables.SysSchemaManager.SYS_SCHEMA_MANAGER;

    /**
     * The table <code>SYS_SCHEMA_VERSION</code>.
     */
    public final SysSchemaVersion SYS_SCHEMA_VERSION = pro.fessional.wings.oracle.database.autogen.tables.SysSchemaVersion.SYS_SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SysCommitJournal.SYS_COMMIT_JOURNAL,
            SysLightSequence.SYS_LIGHT_SEQUENCE,
            SysSchemaManager.SYS_SCHEMA_MANAGER,
            SysSchemaVersion.SYS_SCHEMA_VERSION);
    }
}
