/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.oracle.database.autogen;


import javax.annotation.Generated;

import org.jooq.impl.CatalogImpl;

import pro.fessional.wings.oracle.service.lightid.LightIdAware;


/**
 * The catalog <code></code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    date = "2019-06-15T10:31:23.203Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl implements LightIdAware {

    private static final long serialVersionUID = -1838607679;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }
}
