/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.oracle.database.autogen.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import pro.fessional.wings.oracle.database.autogen.tables.SysLightSequence;
import pro.fessional.wings.oracle.database.autogen.tables.interfaces.ISysLightSequence;
import pro.fessional.wings.oracle.service.lightid.LightIdAware;


/**
 * The table <code>wings_0.SYS_LIGHT_SEQUENCE</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9",
        "schema version:2019052001"
    },
    date = "2019-06-15T10:31:23.203Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "SYS_LIGHT_SEQUENCE", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"SEQ_NAME", "BLOCK_ID"})
})
public class SysLightSequenceRecord extends UpdatableRecordImpl<SysLightSequenceRecord> implements LightIdAware, Record5<String, Integer, Long, Integer, String>, ISysLightSequence {

    private static final long serialVersionUID = 1404766757;

    /**
     * Setter for <code>SYS_LIGHT_SEQUENCE.SEQ_NAME</code>.
     */
    @Override
    public void setSeqName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>SYS_LIGHT_SEQUENCE.SEQ_NAME</code>.
     */
    @Column(name = "SEQ_NAME", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    @Override
    public String getSeqName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>SYS_LIGHT_SEQUENCE.BLOCK_ID</code>.
     */
    @Override
    public void setBlockId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>SYS_LIGHT_SEQUENCE.BLOCK_ID</code>.
     */
    @Column(name = "BLOCK_ID", nullable = false, precision = 10)
    @Override
    public Integer getBlockId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>SYS_LIGHT_SEQUENCE.NEXT_VAL</code>.
     */
    @Override
    public void setNextVal(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>SYS_LIGHT_SEQUENCE.NEXT_VAL</code>.
     */
    @Column(name = "NEXT_VAL", nullable = false, precision = 19)
    @Override
    public Long getNextVal() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>SYS_LIGHT_SEQUENCE.STEP_VAL</code>.
     */
    @Override
    public void setStepVal(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>SYS_LIGHT_SEQUENCE.STEP_VAL</code>.
     */
    @Column(name = "STEP_VAL", nullable = false, precision = 10)
    @Override
    public Integer getStepVal() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>SYS_LIGHT_SEQUENCE.COMMENTS</code>.
     */
    @Override
    public void setComments(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SYS_LIGHT_SEQUENCE.COMMENTS</code>.
     */
    @Column(name = "COMMENTS", nullable = false, length = 200)
    @NotNull
    @Size(max = 200)
    @Override
    public String getComments() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Integer, Long, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Integer, Long, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysLightSequence.SYS_LIGHT_SEQUENCE.SEQ_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SysLightSequence.SYS_LIGHT_SEQUENCE.BLOCK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return SysLightSequence.SYS_LIGHT_SEQUENCE.NEXT_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SysLightSequence.SYS_LIGHT_SEQUENCE.STEP_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysLightSequence.SYS_LIGHT_SEQUENCE.COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getSeqName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getBlockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getNextVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getStepVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSeqName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBlockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getNextVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStepVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLightSequenceRecord value1(String value) {
        setSeqName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLightSequenceRecord value2(Integer value) {
        setBlockId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLightSequenceRecord value3(Long value) {
        setNextVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLightSequenceRecord value4(Integer value) {
        setStepVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLightSequenceRecord value5(String value) {
        setComments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLightSequenceRecord values(String value1, Integer value2, Long value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISysLightSequence from) {
        setSeqName(from.getSeqName());
        setBlockId(from.getBlockId());
        setNextVal(from.getNextVal());
        setStepVal(from.getStepVal());
        setComments(from.getComments());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISysLightSequence> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysLightSequenceRecord
     */
    public SysLightSequenceRecord() {
        super(SysLightSequence.SYS_LIGHT_SEQUENCE);
    }

    /**
     * Create a detached, initialised SysLightSequenceRecord
     */
    public SysLightSequenceRecord(String seqName, Integer blockId, Long nextVal, Integer stepVal, String comments) {
        super(SysLightSequence.SYS_LIGHT_SEQUENCE);

        set(0, seqName);
        set(1, blockId);
        set(2, nextVal);
        set(3, stepVal);
        set(4, comments);
    }
}
