/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.faceless.database.autogen.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import pro.fessional.wings.faceless.database.autogen.tables.SysCommitJournalTable;
import pro.fessional.wings.faceless.database.autogen.tables.interfaces.ISysCommitJournal;


/**
 * The table <code>wings.SYS_COMMIT_JOURNAL</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11",
        "schema version:2019052001"
    },
    date = "2019-08-13T12:54:19.706Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "SYS_COMMIT_JOURNAL")
public class SysCommitJournalRecord extends UpdatableRecordImpl<SysCommitJournalRecord> implements Record6<Long, LocalDateTime, String, String, String, String>, ISysCommitJournal {

    private static final long serialVersionUID = 250137511;

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.ID</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.ID</code>.
     */
    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 19)
    @NotNull
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.CREATE_DT</code>.
     */
    @Override
    public void setCreateDt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.CREATE_DT</code>.
     */
    @Column(name = "CREATE_DT", nullable = false)
    @Override
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.EVENT_NAME</code>.
     */
    @Override
    public void setEventName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.EVENT_NAME</code>.
     */
    @Column(name = "EVENT_NAME", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    @Override
    public String getEventName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.TARGET_KEY</code>.
     */
    @Override
    public void setTargetKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.TARGET_KEY</code>.
     */
    @Column(name = "TARGET_KEY", nullable = false, length = 200)
    @Size(max = 200)
    @Override
    public String getTargetKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.LOGIN_INFO</code>.
     */
    @Override
    public void setLoginInfo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.LOGIN_INFO</code>.
     */
    @Column(name = "LOGIN_INFO", length = 65535)
    @Size(max = 65535)
    @Override
    public String getLoginInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.OTHER_INFO</code>.
     */
    @Override
    public void setOtherInfo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.OTHER_INFO</code>.
     */
    @Column(name = "OTHER_INFO", length = 65535)
    @Size(max = 65535)
    @Override
    public String getOtherInfo() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysCommitJournalTable.SYS_COMMIT_JOURNAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return SysCommitJournalTable.SYS_COMMIT_JOURNAL.CREATE_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysCommitJournalTable.SYS_COMMIT_JOURNAL.EVENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysCommitJournalTable.SYS_COMMIT_JOURNAL.TARGET_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysCommitJournalTable.SYS_COMMIT_JOURNAL.LOGIN_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysCommitJournalTable.SYS_COMMIT_JOURNAL.OTHER_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component2() {
        return getCreateDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEventName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTargetKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLoginInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOtherInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreateDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEventName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTargetKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLoginInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOtherInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysCommitJournalRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysCommitJournalRecord value2(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysCommitJournalRecord value3(String value) {
        setEventName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysCommitJournalRecord value4(String value) {
        setTargetKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysCommitJournalRecord value5(String value) {
        setLoginInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysCommitJournalRecord value6(String value) {
        setOtherInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysCommitJournalRecord values(Long value1, LocalDateTime value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISysCommitJournal from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setEventName(from.getEventName());
        setTargetKey(from.getTargetKey());
        setLoginInfo(from.getLoginInfo());
        setOtherInfo(from.getOtherInfo());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISysCommitJournal> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysCommitJournalRecord
     */
    public SysCommitJournalRecord() {
        super(SysCommitJournalTable.SYS_COMMIT_JOURNAL);
    }

    /**
     * Create a detached, initialised SysCommitJournalRecord
     */
    public SysCommitJournalRecord(Long id, LocalDateTime createDt, String eventName, String targetKey, String loginInfo, String otherInfo) {
        super(SysCommitJournalTable.SYS_COMMIT_JOURNAL);

        set(0, id);
        set(1, createDt);
        set(2, eventName);
        set(3, targetKey);
        set(4, loginInfo);
        set(5, otherInfo);
    }
}
