/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.pojos;


import pro.fessional.wings.warlock.database.autogen.tables.interfaces.IWinUserLogin;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;


/**
 * The table <code>wings_warlock.win_user_login</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102401"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "win_user_login",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_win_user_login_PRIMARY", columnNames = { "id" })
    }
)
public class WinUserLogin implements IWinUserLogin {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          userId;
    private String        authType;
    private String        loginIp;
    private LocalDateTime loginDt;
    private String        terminal;
    private String        remark;

    public WinUserLogin() {}

    public WinUserLogin(IWinUserLogin value) {
        this.id = value.getId();
        this.userId = value.getUserId();
        this.authType = value.getAuthType();
        this.loginIp = value.getLoginIp();
        this.loginDt = value.getLoginDt();
        this.terminal = value.getTerminal();
        this.remark = value.getRemark();
    }

    public WinUserLogin(
        Long          id,
        Long          userId,
        String        authType,
        String        loginIp,
        LocalDateTime loginDt,
        String        terminal,
        String        remark
    ) {
        this.id = id;
        this.userId = userId;
        this.authType = authType;
        this.loginIp = loginIp;
        this.loginDt = loginDt;
        this.terminal = terminal;
        this.remark = remark;
    }

    /**
     * Getter for <code>win_user_login.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, precision = 19)
    @NotNull
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>win_user_login.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>win_user_login.user_id</code>.
     */
    @Column(name = "user_id", nullable = false, precision = 19)
    @Override
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>win_user_login.user_id</code>.
     */
    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>win_user_login.auth_type</code>.
     */
    @Column(name = "auth_type", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    @Override
    public String getAuthType() {
        return this.authType;
    }

    /**
     * Setter for <code>win_user_login.auth_type</code>.
     */
    @Override
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * Getter for <code>win_user_login.login_ip</code>.
     */
    @Column(name = "login_ip", nullable = false, length = 50)
    @Size(max = 50)
    @Override
    public String getLoginIp() {
        return this.loginIp;
    }

    /**
     * Setter for <code>win_user_login.login_ip</code>.
     */
    @Override
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * Getter for <code>win_user_login.login_dt</code>.
     */
    @Column(name = "login_dt", nullable = false, precision = 3)
    @Override
    public LocalDateTime getLoginDt() {
        return this.loginDt;
    }

    /**
     * Setter for <code>win_user_login.login_dt</code>.
     */
    @Override
    public void setLoginDt(LocalDateTime loginDt) {
        this.loginDt = loginDt;
    }

    /**
     * Getter for <code>win_user_login.terminal</code>.
     */
    @Column(name = "terminal", nullable = false, length = 500)
    @Size(max = 500)
    @Override
    public String getTerminal() {
        return this.terminal;
    }

    /**
     * Setter for <code>win_user_login.terminal</code>.
     */
    @Override
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    /**
     * Getter for <code>win_user_login.remark</code>.
     */
    @Column(name = "remark", nullable = false, length = 500)
    @Size(max = 500)
    @Override
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>win_user_login.remark</code>.
     */
    @Override
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WinUserLogin other = (WinUserLogin) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (authType == null) {
            if (other.authType != null)
                return false;
        }
        else if (!authType.equals(other.authType))
            return false;
        if (loginIp == null) {
            if (other.loginIp != null)
                return false;
        }
        else if (!loginIp.equals(other.loginIp))
            return false;
        if (loginDt == null) {
            if (other.loginDt != null)
                return false;
        }
        else if (!loginDt.equals(other.loginDt))
            return false;
        if (terminal == null) {
            if (other.terminal != null)
                return false;
        }
        else if (!terminal.equals(other.terminal))
            return false;
        if (remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!remark.equals(other.remark))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.authType == null) ? 0 : this.authType.hashCode());
        result = prime * result + ((this.loginIp == null) ? 0 : this.loginIp.hashCode());
        result = prime * result + ((this.loginDt == null) ? 0 : this.loginDt.hashCode());
        result = prime * result + ((this.terminal == null) ? 0 : this.terminal.hashCode());
        result = prime * result + ((this.remark == null) ? 0 : this.remark.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WinUserLogin (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(authType);
        sb.append(", ").append(loginIp);
        sb.append(", ").append(loginDt);
        sb.append(", ").append(terminal);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWinUserLogin from) {
        setId(from.getId());
        setUserId(from.getUserId());
        setAuthType(from.getAuthType());
        setLoginIp(from.getLoginIp());
        setLoginDt(from.getLoginDt());
        setTerminal(from.getTerminal());
        setRemark(from.getRemark());
    }

    @Override
    public <E extends IWinUserLogin> E into(E into) {
        into.from(this);
        return into;
    }
}
