/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.pojos;


import pro.fessional.wings.warlock.database.autogen.tables.interfaces.IWinUserRoleMap;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;


/**
 * The table <code>wings_warlock.win_user_role_map</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102402"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "win_user_role_map",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_win_user_role_map_PRIMARY", columnNames = { "refer_user", "grant_role" })
    }
)
public class WinUserRoleMap implements IWinUserRoleMap {

    private static final long serialVersionUID = 1L;

    private Long          referUser;
    private Long          grantRole;
    private LocalDateTime createDt;
    private LocalDateTime modifyDt;
    private LocalDateTime deleteDt;
    private Long          commitId;

    public WinUserRoleMap() {}

    public WinUserRoleMap(IWinUserRoleMap value) {
        this.referUser = value.getReferUser();
        this.grantRole = value.getGrantRole();
        this.createDt = value.getCreateDt();
        this.modifyDt = value.getModifyDt();
        this.deleteDt = value.getDeleteDt();
        this.commitId = value.getCommitId();
    }

    public WinUserRoleMap(
        Long          referUser,
        Long          grantRole,
        LocalDateTime createDt,
        LocalDateTime modifyDt,
        LocalDateTime deleteDt,
        Long          commitId
    ) {
        this.referUser = referUser;
        this.grantRole = grantRole;
        this.createDt = createDt;
        this.modifyDt = modifyDt;
        this.deleteDt = deleteDt;
        this.commitId = commitId;
    }

    /**
     * Getter for <code>win_user_role_map.refer_user</code>.
     */
    @Column(name = "refer_user", nullable = false, precision = 19)
    @NotNull
    @Override
    public Long getReferUser() {
        return this.referUser;
    }

    /**
     * Setter for <code>win_user_role_map.refer_user</code>.
     */
    @Override
    public void setReferUser(Long referUser) {
        this.referUser = referUser;
    }

    /**
     * Getter for <code>win_user_role_map.grant_role</code>.
     */
    @Column(name = "grant_role", nullable = false, precision = 19)
    @NotNull
    @Override
    public Long getGrantRole() {
        return this.grantRole;
    }

    /**
     * Setter for <code>win_user_role_map.grant_role</code>.
     */
    @Override
    public void setGrantRole(Long grantRole) {
        this.grantRole = grantRole;
    }

    /**
     * Getter for <code>win_user_role_map.create_dt</code>.
     */
    @Column(name = "create_dt", nullable = false, precision = 3)
    @Override
    public LocalDateTime getCreateDt() {
        return this.createDt;
    }

    /**
     * Setter for <code>win_user_role_map.create_dt</code>.
     */
    @Override
    public void setCreateDt(LocalDateTime createDt) {
        this.createDt = createDt;
    }

    /**
     * Getter for <code>win_user_role_map.modify_dt</code>.
     */
    @Column(name = "modify_dt", nullable = false, precision = 3)
    @Override
    public LocalDateTime getModifyDt() {
        return this.modifyDt;
    }

    /**
     * Setter for <code>win_user_role_map.modify_dt</code>.
     */
    @Override
    public void setModifyDt(LocalDateTime modifyDt) {
        this.modifyDt = modifyDt;
    }

    /**
     * Getter for <code>win_user_role_map.delete_dt</code>.
     */
    @Column(name = "delete_dt", nullable = false, precision = 3)
    @Override
    public LocalDateTime getDeleteDt() {
        return this.deleteDt;
    }

    /**
     * Setter for <code>win_user_role_map.delete_dt</code>.
     */
    @Override
    public void setDeleteDt(LocalDateTime deleteDt) {
        this.deleteDt = deleteDt;
    }

    /**
     * Getter for <code>win_user_role_map.commit_id</code>.
     */
    @Column(name = "commit_id", nullable = false, precision = 19)
    @NotNull
    @Override
    public Long getCommitId() {
        return this.commitId;
    }

    /**
     * Setter for <code>win_user_role_map.commit_id</code>.
     */
    @Override
    public void setCommitId(Long commitId) {
        this.commitId = commitId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WinUserRoleMap other = (WinUserRoleMap) obj;
        if (referUser == null) {
            if (other.referUser != null)
                return false;
        }
        else if (!referUser.equals(other.referUser))
            return false;
        if (grantRole == null) {
            if (other.grantRole != null)
                return false;
        }
        else if (!grantRole.equals(other.grantRole))
            return false;
        if (createDt == null) {
            if (other.createDt != null)
                return false;
        }
        else if (!createDt.equals(other.createDt))
            return false;
        if (modifyDt == null) {
            if (other.modifyDt != null)
                return false;
        }
        else if (!modifyDt.equals(other.modifyDt))
            return false;
        if (deleteDt == null) {
            if (other.deleteDt != null)
                return false;
        }
        else if (!deleteDt.equals(other.deleteDt))
            return false;
        if (commitId == null) {
            if (other.commitId != null)
                return false;
        }
        else if (!commitId.equals(other.commitId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.referUser == null) ? 0 : this.referUser.hashCode());
        result = prime * result + ((this.grantRole == null) ? 0 : this.grantRole.hashCode());
        result = prime * result + ((this.createDt == null) ? 0 : this.createDt.hashCode());
        result = prime * result + ((this.modifyDt == null) ? 0 : this.modifyDt.hashCode());
        result = prime * result + ((this.deleteDt == null) ? 0 : this.deleteDt.hashCode());
        result = prime * result + ((this.commitId == null) ? 0 : this.commitId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WinUserRoleMap (");

        sb.append(referUser);
        sb.append(", ").append(grantRole);
        sb.append(", ").append(createDt);
        sb.append(", ").append(modifyDt);
        sb.append(", ").append(deleteDt);
        sb.append(", ").append(commitId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWinUserRoleMap from) {
        setReferUser(from.getReferUser());
        setGrantRole(from.getGrantRole());
        setCreateDt(from.getCreateDt());
        setModifyDt(from.getModifyDt());
        setDeleteDt(from.getDeleteDt());
        setCommitId(from.getCommitId());
    }

    @Override
    public <E extends IWinUserRoleMap> E into(E into) {
        into.from(this);
        return into;
    }
}
