/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.interfaces;


import javax.annotation.processing.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * The table <code>wings.win_user_login</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7",
        "schema version:2020102701"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IWinUserLogin extends Serializable {

    /**
     * Setter for <code>win_user_login.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>win_user_login.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>win_user_login.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>win_user_login.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>win_user_login.auth_type</code>.
     */
    public void setAuthType(String value);

    /**
     * Getter for <code>win_user_login.auth_type</code>.
     */
    public String getAuthType();

    /**
     * Setter for <code>win_user_login.login_ip</code>.
     */
    public void setLoginIp(String value);

    /**
     * Getter for <code>win_user_login.login_ip</code>.
     */
    public String getLoginIp();

    /**
     * Setter for <code>win_user_login.login_dt</code>.
     */
    public void setLoginDt(LocalDateTime value);

    /**
     * Getter for <code>win_user_login.login_dt</code>.
     */
    public LocalDateTime getLoginDt();

    /**
     * Setter for <code>win_user_login.terminal</code>.
     */
    public void setTerminal(String value);

    /**
     * Getter for <code>win_user_login.terminal</code>.
     */
    public String getTerminal();

    /**
     * Setter for <code>win_user_login.details</code>.
     */
    public void setDetails(String value);

    /**
     * Getter for <code>win_user_login.details</code>.
     */
    public String getDetails();

    /**
     * Setter for <code>win_user_login.failed</code>.
     */
    public void setFailed(Boolean value);

    /**
     * Getter for <code>win_user_login.failed</code>.
     */
    public Boolean getFailed();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IWinUserLogin
     */
    public void from(IWinUserLogin from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IWinUserLogin
     */
    public <E extends IWinUserLogin> E into(E into);
}
