/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.faceless.database.autogen.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import pro.fessional.wings.faceless.database.autogen.tables.Tst中文也分表Table;
import pro.fessional.wings.faceless.database.autogen.tables.pojos.Tst中文也分表;
import pro.fessional.wings.faceless.database.autogen.tables.records.Tst中文也分表Record;


/**
 * The table <code>wings_0.TST_中文也分表</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class Tst中文也分表Dao extends DAOImpl<Tst中文也分表Record, Tst中文也分表, Long> {

    /**
     * Create a new Tst中文也分表Dao without any configuration
     */
    public Tst中文也分表Dao() {
        super(Tst中文也分表Table.TST_中文也分表, Tst中文也分表.class);
    }

    /**
     * Create a new Tst中文也分表Dao with an attached configuration
     */
    @Autowired
    public Tst中文也分表Dao(Configuration configuration) {
        super(Tst中文也分表Table.TST_中文也分表, Tst中文也分表.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(Tst中文也分表 object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<Tst中文也分表> fetchById(Long... values) {
        return fetch(Tst中文也分表Table.TST_中文也分表.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public Tst中文也分表 fetchOneById(Long value) {
        return fetchOne(Tst中文也分表Table.TST_中文也分表.ID, value);
    }

    /**
     * Fetch records that have <code>CREATE_DT IN (values)</code>
     */
    public List<Tst中文也分表> fetchByCreateDt(LocalDateTime... values) {
        return fetch(Tst中文也分表Table.TST_中文也分表.CREATE_DT, values);
    }

    /**
     * Fetch records that have <code>MODIFY_DT IN (values)</code>
     */
    public List<Tst中文也分表> fetchByModifyDt(LocalDateTime... values) {
        return fetch(Tst中文也分表Table.TST_中文也分表.MODIFY_DT, values);
    }

    /**
     * Fetch records that have <code>COMMIT_ID IN (values)</code>
     */
    public List<Tst中文也分表> fetchByCommitId(Long... values) {
        return fetch(Tst中文也分表Table.TST_中文也分表.COMMIT_ID, values);
    }

    /**
     * Fetch records that have <code>LOGIN_INFO IN (values)</code>
     */
    public List<Tst中文也分表> fetchByLoginInfo(String... values) {
        return fetch(Tst中文也分表Table.TST_中文也分表.LOGIN_INFO, values);
    }

    /**
     * Fetch records that have <code>OTHER_INFO IN (values)</code>
     */
    public List<Tst中文也分表> fetchByOtherInfo(String... values) {
        return fetch(Tst中文也分表Table.TST_中文也分表.OTHER_INFO, values);
    }
}
