/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.tiny.mail.database.autogen;


import pro.fessional.wings.tiny.mail.database.autogen.tables.WinMailSenderTable;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7",
        "schema version:2020102701"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablesTinyMail {

    /**
     * The table <code>win_mail_sender</code>.
     */
    public static final WinMailSenderTable WinMailSender = WinMailSenderTable.WinMailSender;
}
