/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.tiny.task.database.autogen;


import pro.fessional.wings.tiny.task.database.autogen.tables.WinTaskDefineTable;
import pro.fessional.wings.tiny.task.database.autogen.tables.WinTaskResultTable;

import jakarta.annotation.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16",
        "schema version:2020102601"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablesTinyTask {

    /**
     * The table <code>win_task_define</code>.
     */
    public static final WinTaskDefineTable WinTaskDefine = WinTaskDefineTable.WinTaskDefine;

    /**
     * The table <code>win_task_result</code>.
     */
    public static final WinTaskResultTable WinTaskResult = WinTaskResultTable.WinTaskResult;
}
