/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.example.database.autogen.tables.interfaces;


import pro.fessional.wings.faceless.service.journal.JournalAware;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * The table <code>wings_example.win_auth_role</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.3",
        "schema version:2019070403"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "win_auth_role",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_win_auth_role_PRIMARY", columnNames = { "id" })
    }
)
public interface IWinAuthRole extends JournalAware, Serializable {

    /**
     * Setter for <code>win_auth_role.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>win_auth_role.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, precision = 19)
    @NotNull
    public Long getId();

    /**
     * Setter for <code>win_auth_role.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>win_auth_role.create_dt</code>.
     */
    @Column(name = "create_dt", nullable = false, precision = 3)
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>win_auth_role.modify_dt</code>.
     */
    public void setModifyDt(LocalDateTime value);

    /**
     * Getter for <code>win_auth_role.modify_dt</code>.
     */
    @Column(name = "modify_dt", nullable = false, precision = 3)
    public LocalDateTime getModifyDt();

    /**
     * Setter for <code>win_auth_role.delete_dt</code>.
     */
    public void setDeleteDt(LocalDateTime value);

    /**
     * Getter for <code>win_auth_role.delete_dt</code>.
     */
    @Column(name = "delete_dt", nullable = false, precision = 3)
    public LocalDateTime getDeleteDt();

    /**
     * Setter for <code>win_auth_role.commit_id</code>.
     */
    public void setCommitId(Long value);

    /**
     * Getter for <code>win_auth_role.commit_id</code>.
     */
    @Column(name = "commit_id", nullable = false, precision = 19)
    @NotNull
    public Long getCommitId();

    /**
     * Setter for <code>win_auth_role.role_type</code>.
     */
    public void setRoleType(Integer value);

    /**
     * Getter for <code>win_auth_role.role_type</code>.
     */
    @Column(name = "role_type", nullable = false, precision = 10)
    @NotNull
    public Integer getRoleType();

    /**
     * Setter for <code>win_auth_role.role_name</code>.
     */
    public void setRoleName(String value);

    /**
     * Getter for <code>win_auth_role.role_name</code>.
     */
    @Column(name = "role_name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getRoleName();

    /**
     * Setter for <code>win_auth_role.desc</code>.
     */
    public void setDesc(String value);

    /**
     * Getter for <code>win_auth_role.desc</code>.
     */
    @Column(name = "desc", nullable = false, length = 200)
    @Size(max = 200)
    public String getDesc();

    /**
     * Setter for <code>win_auth_role.auth_set</code>.
     */
    public void setAuthSet(String value);

    /**
     * Getter for <code>win_auth_role.auth_set</code>.
     */
    @Column(name = "auth_set", nullable = false, length = 3000)
    @NotNull
    @Size(max = 3000)
    public String getAuthSet();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IWinAuthRole
     */
    public void from(IWinAuthRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IWinAuthRole
     */
    public <E extends IWinAuthRole> E into(E into);
}
