/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen;


import pro.fessional.wings.warlock.database.autogen.tables.SysConstantEnumTable;
import pro.fessional.wings.warlock.database.autogen.tables.SysStandardI18nTable;
import pro.fessional.wings.warlock.database.autogen.tables.WinUserAnthnTable;
import pro.fessional.wings.warlock.database.autogen.tables.WinUserBasicTable;
import pro.fessional.wings.warlock.database.autogen.tables.WinUserLoginTable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102401"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sys_constant_enum</code>.
     */
    public static final SysConstantEnumTable SysConstantEnum = SysConstantEnumTable.SysConstantEnum;

    /**
     * The table <code>sys_standard_i18n</code>.
     */
    public static final SysStandardI18nTable SysStandardI18n = SysStandardI18nTable.SysStandardI18n;

    /**
     * The table <code>win_user_anthn</code>.
     */
    public static final WinUserAnthnTable WinUserAnthn = WinUserAnthnTable.WinUserAnthn;

    /**
     * The table <code>win_user_basic</code>.
     */
    public static final WinUserBasicTable WinUserBasic = WinUserBasicTable.WinUserBasic;

    /**
     * The table <code>win_user_login</code>.
     */
    public static final WinUserLoginTable WinUserLogin = WinUserLoginTable.WinUserLogin;
}
