/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.interfaces;


import pro.fessional.wings.faceless.service.journal.JournalAware;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * The table <code>wings_warlock.win_role_perm_map</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102402"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "win_role_perm_map",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_win_role_perm_map_PRIMARY", columnNames = { "refer_role", "grant_perm" })
    }
)
public interface IWinRolePermMap extends JournalAware, Serializable {

    /**
     * Setter for <code>win_role_perm_map.refer_role</code>.
     */
    public void setReferRole(Long value);

    /**
     * Getter for <code>win_role_perm_map.refer_role</code>.
     */
    @Column(name = "refer_role", nullable = false, precision = 19)
    @NotNull
    public Long getReferRole();

    /**
     * Setter for <code>win_role_perm_map.grant_perm</code>.
     */
    public void setGrantPerm(Long value);

    /**
     * Getter for <code>win_role_perm_map.grant_perm</code>.
     */
    @Column(name = "grant_perm", nullable = false, precision = 19)
    @NotNull
    public Long getGrantPerm();

    /**
     * Setter for <code>win_role_perm_map.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>win_role_perm_map.create_dt</code>.
     */
    @Column(name = "create_dt", nullable = false, precision = 3)
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>win_role_perm_map.modify_dt</code>.
     */
    public void setModifyDt(LocalDateTime value);

    /**
     * Getter for <code>win_role_perm_map.modify_dt</code>.
     */
    @Column(name = "modify_dt", nullable = false, precision = 3)
    public LocalDateTime getModifyDt();

    /**
     * Setter for <code>win_role_perm_map.delete_dt</code>.
     */
    public void setDeleteDt(LocalDateTime value);

    /**
     * Getter for <code>win_role_perm_map.delete_dt</code>.
     */
    @Column(name = "delete_dt", nullable = false, precision = 3)
    public LocalDateTime getDeleteDt();

    /**
     * Setter for <code>win_role_perm_map.commit_id</code>.
     */
    public void setCommitId(Long value);

    /**
     * Getter for <code>win_role_perm_map.commit_id</code>.
     */
    @Column(name = "commit_id", nullable = false, precision = 19)
    @NotNull
    public Long getCommitId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IWinRolePermMap
     */
    public void from(IWinRolePermMap from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IWinRolePermMap
     */
    public <E extends IWinRolePermMap> E into(E into);
}
