/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.interfaces;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * The table <code>wings_warlock.win_user_login</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102401"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "win_user_login",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_win_user_login_PRIMARY", columnNames = { "id" })
    }
)
public interface IWinUserLogin extends Serializable {

    /**
     * Setter for <code>win_user_login.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>win_user_login.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, precision = 19)
    @NotNull
    public Long getId();

    /**
     * Setter for <code>win_user_login.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>win_user_login.user_id</code>.
     */
    @Column(name = "user_id", nullable = false, precision = 19)
    public Long getUserId();

    /**
     * Setter for <code>win_user_login.auth_type</code>.
     */
    public void setAuthType(String value);

    /**
     * Getter for <code>win_user_login.auth_type</code>.
     */
    @Column(name = "auth_type", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    public String getAuthType();

    /**
     * Setter for <code>win_user_login.login_ip</code>.
     */
    public void setLoginIp(String value);

    /**
     * Getter for <code>win_user_login.login_ip</code>.
     */
    @Column(name = "login_ip", nullable = false, length = 50)
    @Size(max = 50)
    public String getLoginIp();

    /**
     * Setter for <code>win_user_login.login_dt</code>.
     */
    public void setLoginDt(LocalDateTime value);

    /**
     * Getter for <code>win_user_login.login_dt</code>.
     */
    @Column(name = "login_dt", nullable = false, precision = 3)
    public LocalDateTime getLoginDt();

    /**
     * Setter for <code>win_user_login.terminal</code>.
     */
    public void setTerminal(String value);

    /**
     * Getter for <code>win_user_login.terminal</code>.
     */
    @Column(name = "terminal", nullable = false, length = 500)
    @Size(max = 500)
    public String getTerminal();

    /**
     * Setter for <code>win_user_login.remark</code>.
     */
    public void setRemark(String value);

    /**
     * Getter for <code>win_user_login.remark</code>.
     */
    @Column(name = "remark", nullable = false, length = 500)
    @Size(max = 500)
    public String getRemark();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IWinUserLogin
     */
    public void from(IWinUserLogin from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IWinUserLogin
     */
    public <E extends IWinUserLogin> E into(E into);
}
