/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.interfaces;


import pro.fessional.wings.faceless.service.journal.JournalAware;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * The table <code>wings_warlock.win_perm_entry</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102402"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "win_perm_entry",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_win_perm_entry_PRIMARY", columnNames = { "id" })
    }
)
public interface IWinPermEntry extends JournalAware, Serializable {

    /**
     * Setter for <code>win_perm_entry.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>win_perm_entry.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, precision = 19)
    @NotNull
    public Long getId();

    /**
     * Setter for <code>win_perm_entry.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>win_perm_entry.create_dt</code>.
     */
    @Column(name = "create_dt", nullable = false, precision = 3)
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>win_perm_entry.modify_dt</code>.
     */
    public void setModifyDt(LocalDateTime value);

    /**
     * Getter for <code>win_perm_entry.modify_dt</code>.
     */
    @Column(name = "modify_dt", nullable = false, precision = 3)
    public LocalDateTime getModifyDt();

    /**
     * Setter for <code>win_perm_entry.delete_dt</code>.
     */
    public void setDeleteDt(LocalDateTime value);

    /**
     * Getter for <code>win_perm_entry.delete_dt</code>.
     */
    @Column(name = "delete_dt", nullable = false, precision = 3)
    public LocalDateTime getDeleteDt();

    /**
     * Setter for <code>win_perm_entry.commit_id</code>.
     */
    public void setCommitId(Long value);

    /**
     * Getter for <code>win_perm_entry.commit_id</code>.
     */
    @Column(name = "commit_id", nullable = false, precision = 19)
    @NotNull
    public Long getCommitId();

    /**
     * Setter for <code>win_perm_entry.scopes</code>.
     */
    public void setScopes(String value);

    /**
     * Getter for <code>win_perm_entry.scopes</code>.
     */
    @Column(name = "scopes", nullable = false, length = 200)
    @NotNull
    @Size(max = 200)
    public String getScopes();

    /**
     * Setter for <code>win_perm_entry.action</code>.
     */
    public void setAction(String value);

    /**
     * Getter for <code>win_perm_entry.action</code>.
     */
    @Column(name = "action", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getAction();

    /**
     * Setter for <code>win_perm_entry.remark</code>.
     */
    public void setRemark(String value);

    /**
     * Getter for <code>win_perm_entry.remark</code>.
     */
    @Column(name = "remark", nullable = false, length = 500)
    @Size(max = 500)
    public String getRemark();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IWinPermEntry
     */
    public void from(IWinPermEntry from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IWinPermEntry
     */
    public <E extends IWinPermEntry> E into(E into);
}
