/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.interfaces;


import pro.fessional.wings.faceless.service.journal.JournalAware;
import pro.fessional.wings.warlock.enums.autogen.UserGender;
import pro.fessional.wings.warlock.enums.autogen.UserStatus;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Locale;


/**
 * The table <code>wings_warlock.win_user_basic</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102401"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "win_user_basic",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_win_user_basic_PRIMARY", columnNames = { "id" })
    }
)
public interface IWinUserBasic extends JournalAware, Serializable {

    /**
     * Setter for <code>win_user_basic.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>win_user_basic.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, precision = 19)
    @NotNull
    public Long getId();

    /**
     * Setter for <code>win_user_basic.create_dt</code>.
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>win_user_basic.create_dt</code>.
     */
    @Column(name = "create_dt", nullable = false, precision = 3)
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>win_user_basic.modify_dt</code>.
     */
    public void setModifyDt(LocalDateTime value);

    /**
     * Getter for <code>win_user_basic.modify_dt</code>.
     */
    @Column(name = "modify_dt", nullable = false, precision = 3)
    public LocalDateTime getModifyDt();

    /**
     * Setter for <code>win_user_basic.delete_dt</code>.
     */
    public void setDeleteDt(LocalDateTime value);

    /**
     * Getter for <code>win_user_basic.delete_dt</code>.
     */
    @Column(name = "delete_dt", nullable = false, precision = 3)
    public LocalDateTime getDeleteDt();

    /**
     * Setter for <code>win_user_basic.commit_id</code>.
     */
    public void setCommitId(Long value);

    /**
     * Getter for <code>win_user_basic.commit_id</code>.
     */
    @Column(name = "commit_id", nullable = false, precision = 19)
    @NotNull
    public Long getCommitId();

    /**
     * Setter for <code>win_user_basic.nickname</code>.
     */
    public void setNickname(String value);

    /**
     * Getter for <code>win_user_basic.nickname</code>.
     */
    @Column(name = "nickname", nullable = false, length = 50)
    @Size(max = 50)
    public String getNickname();

    /**
     * Setter for <code>win_user_basic.gender</code>.
     */
    public void setGender(UserGender value);

    /**
     * Getter for <code>win_user_basic.gender</code>.
     */
    @Column(name = "gender", nullable = false, precision = 10)
    public UserGender getGender();

    /**
     * Setter for <code>win_user_basic.avatar</code>.
     */
    public void setAvatar(String value);

    /**
     * Getter for <code>win_user_basic.avatar</code>.
     */
    @Column(name = "avatar", nullable = false, length = 200)
    @Size(max = 200)
    public String getAvatar();

    /**
     * Setter for <code>win_user_basic.locale</code>.
     */
    public void setLocale(Locale value);

    /**
     * Getter for <code>win_user_basic.locale</code>.
     */
    @Column(name = "locale", nullable = false, length = 5)
    public Locale getLocale();

    /**
     * Setter for <code>win_user_basic.zoneid</code>.
     */
    public void setZoneid(ZoneId value);

    /**
     * Getter for <code>win_user_basic.zoneid</code>.
     */
    @Column(name = "zoneid", nullable = false, precision = 10)
    public ZoneId getZoneid();

    /**
     * Setter for <code>win_user_basic.remark</code>.
     */
    public void setRemark(String value);

    /**
     * Getter for <code>win_user_basic.remark</code>.
     */
    @Column(name = "remark", nullable = false, length = 500)
    @Size(max = 500)
    public String getRemark();

    /**
     * Setter for <code>win_user_basic.status</code>.
     */
    public void setStatus(UserStatus value);

    /**
     * Getter for <code>win_user_basic.status</code>.
     */
    @Column(name = "status", nullable = false, precision = 10)
    public UserStatus getStatus();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IWinUserBasic
     */
    public void from(IWinUserBasic from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IWinUserBasic
     */
    public <E extends IWinUserBasic> E into(E into);
}
