# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
POST http://localhost:8080/login.json
Content-Type: application/x-www-form-urlencoded

username=trydofor&password=moilioncircle


### 需要权限
# 如果access_token 不对则 401 (Unauthorized)
# 需要用login得到的access_token
GET http://localhost:8080/user/create.json
Authorization: Bearer WG-W44KXU-Q7P4A-ZTTK5L8NFNTA2H

### 需要权限
# 如果access_token 不对则 401 (Unauthorized)
# 需要用login得到的access_token
GET http://localhost:8080/user/create.json?access_token=WG-W44KXU-Q7P4A-ZTTK5L8NFNTA2H

###
GET http://localhost:8080/logout.json
Authorization: Bearer WG-W44KXU-Q7P4A-ZTTK5L8NFNTA2H




