### login-page
GET {{host}}/user/login.json

## repeat wings-slardar-pass and then MD5, that is md5(pass+pass)
#
### login-proc
POST {{host}}/user/login-proc.json
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

username=wings-slardar-user2&password=5DDEEB6C6F9812EE9C7CCF6FC82A50DD

### login-proc
POST {{host}}/sms/login-proc.json
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

username=wings-slardar-user2&password=5DDEEB6C6F9812EE9C7CCF6FC82A50DD

###
GET {{host}}/authed/see-user.json

###
GET {{host}}/user/logout.json

###
GET {{host}}/swagger-ui/index.html
