/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.tiny.grow.database.autogen;


import pro.fessional.wings.tiny.grow.database.autogen.tables.WinGrowTrackTable;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9",
        "schema version:2020102801"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablesTinyGrow {

    /**
     * The table <code>win_grow_track</code>.
     */
    public static final WinGrowTrackTable WinGrowTrack = WinGrowTrackTable.WinGrowTrack;
}
