CREATE TABLE `SYS_SCHEMA_JOURNAL`
(
  `TABLE_NAME` varchar(100) NOT NULL COMMENT '主表表名',
  `CREATE_DT`  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日时',
  `MODIFY_DT`  datetime     NOT NULL DEFAULT '1000-01-01' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日时',
  `COMMIT_ID`  bigint(20)   NOT NULL COMMENT '提交ID',
  `DDL_UPDTBL` TEXT         NOT NULL COMMENT '更新的跟踪表DDL',
  `DDL_UPDTRG` TEXT         NOT NULL COMMENT '更新的触发器DDL',
  `DDL_DELTBL` TEXT         NOT NULL COMMENT '删除的跟踪表DDL',
  `DDL_DELTRG` TEXT         NOT NULL COMMENT '删除的触发器DDL',
  `LOG_UPDATE` datetime     NOT NULL DEFAULT '1000-01-01' COMMENT '开始跟踪更新的日时',
  `LOG_DELETE` datetime     NOT NULL DEFAULT '1000-01-01' COMMENT '开始跟踪删除的日时',
  PRIMARY KEY (`TABLE_NAME`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='表结构管理';

CREATE TABLE `SYS_SCHEMA_VERSION`
(
  `REVISION`  bigint(20) NOT NULL COMMENT '版本号+修订号',
  `CREATE_DT` datetime   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日时',
  `MODIFY_DT` datetime   NOT NULL DEFAULT '1000-01-01' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日时',
  `COMMIT_ID` bigint(20) NOT NULL COMMENT '提交ID',
  `UPTO_SQL`  text       NOT NULL COMMENT '升级脚本',
  `UNDO_SQL`  text       NOT NULL COMMENT '降级脚本',
  `APPLY_DT`  datetime   NOT NULL DEFAULT '1000-01-01' COMMENT '执行日时',
  PRIMARY KEY (`REVISION`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='表结构版本';

-- SYS_SCHEMA_JOURNAL@plain
REPLACE INTO `SYS_SCHEMA_JOURNAL`(`TABLE_NAME`, `COMMIT_ID`, `DDL_UPDTBL`, `DDL_UPDTRG`, `DDL_DELTBL`, `DDL_DELTRG`)
VALUES ('SYS_SCHEMA_JOURNAL', 0, '', '', '', ''),
       ('SYS_SCHEMA_VERSION', 0, '', '', '', '');

-- SYS_SCHEMA_VERSION@plain
INSERT IGNORE `SYS_SCHEMA_VERSION`(`REVISION`, `COMMIT_ID`, `UPTO_SQL`, `UNDO_SQL`, `APPLY_DT`)
VALUES (2019051201, 0, '', '', NOW());