/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.example.database.autogen;


import pro.fessional.wings.example.database.autogen.tables.SysConstantEnumTable;
import pro.fessional.wings.example.database.autogen.tables.SysStandardI18nTable;
import pro.fessional.wings.example.database.autogen.tables.WinAuthRoleTable;
import pro.fessional.wings.example.database.autogen.tables.WinUserLoginTable;
import pro.fessional.wings.example.database.autogen.tables.WinUserTable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.3",
        "schema version:2019070403"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sys_constant_enum</code>.
     */
    public static final SysConstantEnumTable SysConstantEnum = SysConstantEnumTable.SysConstantEnum;

    /**
     * The table <code>sys_standard_i18n</code>.
     */
    public static final SysStandardI18nTable SysStandardI18n = SysStandardI18nTable.SysStandardI18n;

    /**
     * The table <code>win_auth_role</code>.
     */
    public static final WinAuthRoleTable WinAuthRole = WinAuthRoleTable.WinAuthRole;

    /**
     * The table <code>win_user</code>.
     */
    public static final WinUserTable WinUser = WinUserTable.WinUser;

    /**
     * The table <code>win_user_login</code>.
     */
    public static final WinUserLoginTable WinUserLogin = WinUserLoginTable.WinUserLogin;
}
