### login-page
GET {{host}}/user/login.json

# wings-slardar-pass 的 复制一次，然后MD5，即md5(pass+pass)
#
### login-proc
POST {{host}}/user/login-proc.json
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

username=wings-slardar-user2&password=F9EC9CF4EA9EEEE69FC01AA44638087F

### login-proc
POST {{host}}/sms/login-proc.json
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

username=wings-slardar-user2&password=F9EC9CF4EA9EEEE69FC01AA44638087F

###
GET {{host}}/authed/see-user.json

###
GET {{host}}/user/logout.json

###
GET {{host}}/swagger-ui/index.html
