/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.faceless.database.autogen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import pro.fessional.wings.faceless.service.journal.JournalAware;


/**
 * The table <code>wings_0.TST_中文也分表</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "TST_中文也分表")
public interface ITst中文也分表 extends JournalAware, Serializable {

    /**
     * Setter for <code>TST_中文也分表.ID</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>TST_中文也分表.ID</code>.
     */
    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 19)
    @NotNull
    public Long getId();

    /**
     * Setter for <code>TST_中文也分表.CREATE_DT</code>.
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>TST_中文也分表.CREATE_DT</code>.
     */
    @Column(name = "CREATE_DT", nullable = false)
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>TST_中文也分表.MODIFY_DT</code>.
     */
    public void setModifyDt(LocalDateTime value);

    /**
     * Getter for <code>TST_中文也分表.MODIFY_DT</code>.
     */
    @Column(name = "MODIFY_DT", nullable = false)
    public LocalDateTime getModifyDt();

    /**
     * Setter for <code>TST_中文也分表.COMMIT_ID</code>.
     */
    public void setCommitId(Long value);

    /**
     * Getter for <code>TST_中文也分表.COMMIT_ID</code>.
     */
    @Column(name = "COMMIT_ID", nullable = false, precision = 19)
    @NotNull
    public Long getCommitId();

    /**
     * Setter for <code>TST_中文也分表.LOGIN_INFO</code>.
     */
    public void setLoginInfo(String value);

    /**
     * Getter for <code>TST_中文也分表.LOGIN_INFO</code>.
     */
    @Column(name = "LOGIN_INFO", length = 65535)
    @Size(max = 65535)
    public String getLoginInfo();

    /**
     * Setter for <code>TST_中文也分表.OTHER_INFO</code>.
     */
    public void setOtherInfo(String value);

    /**
     * Getter for <code>TST_中文也分表.OTHER_INFO</code>.
     */
    @Column(name = "OTHER_INFO", length = 65535)
    @Size(max = 65535)
    public String getOtherInfo();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITst中文也分表
     */
    public void from(pro.fessional.wings.faceless.database.autogen.tables.interfaces.ITst中文也分表 from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITst中文也分表
     */
    public <E extends pro.fessional.wings.faceless.database.autogen.tables.interfaces.ITst中文也分表> E into(E into);
}
