/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import pro.fessional.wings.warlock.database.autogen.tables.WinRoleEntryTable;
import pro.fessional.wings.warlock.database.autogen.tables.interfaces.IWinRoleEntry;
import pro.fessional.wings.warlock.database.autogen.tables.pojos.WinRoleEntry;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;


/**
 * The table <code>wings.win_role_entry</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7",
        "schema version:2020102701"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WinRoleEntryRecord extends UpdatableRecordImpl<WinRoleEntryRecord> implements Record7<Long, LocalDateTime, LocalDateTime, LocalDateTime, Long, String, String>, IWinRoleEntry {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>win_role_entry.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>win_role_entry.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>win_role_entry.create_dt</code>.
     */
    @Override
    public void setCreateDt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>win_role_entry.create_dt</code>.
     */
    @Override
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>win_role_entry.modify_dt</code>.
     */
    @Override
    public void setModifyDt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>win_role_entry.modify_dt</code>.
     */
    @Override
    public LocalDateTime getModifyDt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>win_role_entry.delete_dt</code>.
     */
    @Override
    public void setDeleteDt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>win_role_entry.delete_dt</code>.
     */
    @Override
    public LocalDateTime getDeleteDt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>win_role_entry.commit_id</code>.
     */
    @Override
    public void setCommitId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>win_role_entry.commit_id</code>.
     */
    @Override
    public Long getCommitId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>win_role_entry.name</code>.
     */
    @Override
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>win_role_entry.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>win_role_entry.remark</code>.
     */
    @Override
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>win_role_entry.remark</code>.
     */
    @Override
    public String getRemark() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, LocalDateTime, LocalDateTime, LocalDateTime, Long, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, LocalDateTime, LocalDateTime, LocalDateTime, Long, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WinRoleEntryTable.WinRoleEntry.Id;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return WinRoleEntryTable.WinRoleEntry.CreateDt;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return WinRoleEntryTable.WinRoleEntry.ModifyDt;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return WinRoleEntryTable.WinRoleEntry.DeleteDt;
    }

    @Override
    public Field<Long> field5() {
        return WinRoleEntryTable.WinRoleEntry.CommitId;
    }

    @Override
    public Field<String> field6() {
        return WinRoleEntryTable.WinRoleEntry.Name;
    }

    @Override
    public Field<String> field7() {
        return WinRoleEntryTable.WinRoleEntry.Remark;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreateDt();
    }

    @Override
    public LocalDateTime component3() {
        return getModifyDt();
    }

    @Override
    public LocalDateTime component4() {
        return getDeleteDt();
    }

    @Override
    public Long component5() {
        return getCommitId();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getRemark();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreateDt();
    }

    @Override
    public LocalDateTime value3() {
        return getModifyDt();
    }

    @Override
    public LocalDateTime value4() {
        return getDeleteDt();
    }

    @Override
    public Long value5() {
        return getCommitId();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getRemark();
    }

    @Override
    public WinRoleEntryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WinRoleEntryRecord value2(LocalDateTime value) {
        setCreateDt(value);
        return this;
    }

    @Override
    public WinRoleEntryRecord value3(LocalDateTime value) {
        setModifyDt(value);
        return this;
    }

    @Override
    public WinRoleEntryRecord value4(LocalDateTime value) {
        setDeleteDt(value);
        return this;
    }

    @Override
    public WinRoleEntryRecord value5(Long value) {
        setCommitId(value);
        return this;
    }

    @Override
    public WinRoleEntryRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public WinRoleEntryRecord value7(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public WinRoleEntryRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, Long value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWinRoleEntry from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setModifyDt(from.getModifyDt());
        setDeleteDt(from.getDeleteDt());
        setCommitId(from.getCommitId());
        setName(from.getName());
        setRemark(from.getRemark());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IWinRoleEntry> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WinRoleEntryRecord
     */
    public WinRoleEntryRecord() {
        super(WinRoleEntryTable.WinRoleEntry);
    }

    /**
     * Create a detached, initialised WinRoleEntryRecord
     */
    public WinRoleEntryRecord(Long id, LocalDateTime createDt, LocalDateTime modifyDt, LocalDateTime deleteDt, Long commitId, String name, String remark) {
        super(WinRoleEntryTable.WinRoleEntry);

        setId(id);
        setCreateDt(createDt);
        setModifyDt(modifyDt);
        setDeleteDt(deleteDt);
        setCommitId(commitId);
        setName(name);
        setRemark(remark);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WinRoleEntryRecord
     */
    public WinRoleEntryRecord(WinRoleEntry value) {
        super(WinRoleEntryTable.WinRoleEntry);

        if (value != null) {
            setId(value.getId());
            setCreateDt(value.getCreateDt());
            setModifyDt(value.getModifyDt());
            setDeleteDt(value.getDeleteDt());
            setCommitId(value.getCommitId());
            setName(value.getName());
            setRemark(value.getRemark());
            resetChangedOnNotNull();
        }
    }
}
