/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.example.database.autogen.tables.daos;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import pro.fessional.wings.example.database.autogen.tables.WinUserTable;
import pro.fessional.wings.example.database.autogen.tables.pojos.WinUser;
import pro.fessional.wings.example.database.autogen.tables.records.WinUserRecord;
import pro.fessional.wings.faceless.database.common.WingsJooqDaoImpl;


/**
 * The table <code>wings_0.win_user</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4",
        "schema version:2019070403"
    },
    date = "2020-06-16T08:45:49.702Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class WinUserDao extends WingsJooqDaoImpl<WinUserTable, WinUserRecord, WinUser, Long> {

    /**
     * Create a new WinUserDao without any configuration
     */
    public WinUserDao() {
        super(WinUserTable.WinUser, WinUserTable.asZ7, WinUser.class);
    }

    /**
     * Create a new WinUserDao with an attached configuration
     */
    @Autowired
    public WinUserDao(Configuration configuration) {
        super(WinUserTable.WinUser, WinUserTable.asZ7, WinUser.class, configuration);
    }

    @Override
    public Long getId(WinUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<WinUser> fetchById(Long... values) {
        return fetch(WinUserTable.asZ7.Id, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public WinUser fetchOneById(Long value) {
        return fetchOne(WinUserTable.asZ7.Id, value);
    }

    /**
     * Fetch records that have <code>create_dt IN (values)</code>
     */
    public List<WinUser> fetchByCreateDt(LocalDateTime... values) {
        return fetch(WinUserTable.asZ7.CreateDt, values);
    }

    /**
     * Fetch records that have <code>modify_dt IN (values)</code>
     */
    public List<WinUser> fetchByModifyDt(LocalDateTime... values) {
        return fetch(WinUserTable.asZ7.ModifyDt, values);
    }

    /**
     * Fetch records that have <code>delete_dt IN (values)</code>
     */
    public List<WinUser> fetchByDeleteDt(LocalDateTime... values) {
        return fetch(WinUserTable.asZ7.DeleteDt, values);
    }

    /**
     * Fetch records that have <code>commit_id IN (values)</code>
     */
    public List<WinUser> fetchByCommitId(Long... values) {
        return fetch(WinUserTable.asZ7.CommitId, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<WinUser> fetchByName(String... values) {
        return fetch(WinUserTable.asZ7.Name, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<WinUser> fetchByGender(Integer... values) {
        return fetch(WinUserTable.asZ7.Gender, values);
    }

    /**
     * Fetch records that have <code>birth IN (values)</code>
     */
    public List<WinUser> fetchByBirth(LocalDate... values) {
        return fetch(WinUserTable.asZ7.Birth, values);
    }

    /**
     * Fetch records that have <code>avatar IN (values)</code>
     */
    public List<WinUser> fetchByAvatar(String... values) {
        return fetch(WinUserTable.asZ7.Avatar, values);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<WinUser> fetchByCountry(String... values) {
        return fetch(WinUserTable.asZ7.Country, values);
    }

    /**
     * Fetch records that have <code>language IN (values)</code>
     */
    public List<WinUser> fetchByLanguage(String... values) {
        return fetch(WinUserTable.asZ7.Language, values);
    }

    /**
     * Fetch records that have <code>timezone IN (values)</code>
     */
    public List<WinUser> fetchByTimezone(Integer... values) {
        return fetch(WinUserTable.asZ7.Timezone, values);
    }

    /**
     * Fetch records that have <code>auth_set IN (values)</code>
     */
    public List<WinUser> fetchByAuthSet(String... values) {
        return fetch(WinUserTable.asZ7.AuthSet, values);
    }

    /**
     * Fetch records that have <code>role_set IN (values)</code>
     */
    public List<WinUser> fetchByRoleSet(String... values) {
        return fetch(WinUserTable.asZ7.RoleSet, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<WinUser> fetchByStatus(Integer... values) {
        return fetch(WinUserTable.asZ7.Status, values);
    }
}
