/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables.pojos;


import pro.fessional.wings.warlock.database.autogen.tables.interfaces.IWinPermEntry;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;
import java.util.function.Predicate;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;


/**
 * The table <code>wings.win_perm_entry</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9",
        "schema version:2020102701"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WinPermEntry implements IWinPermEntry {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDateTime createDt;
    private LocalDateTime modifyDt;
    private LocalDateTime deleteDt;
    private Long commitId;
    private String scopes;
    private String action;
    private String remark;

    public WinPermEntry() {}

    public WinPermEntry(IWinPermEntry value) {
        this.id = value.getId();
        this.createDt = value.getCreateDt();
        this.modifyDt = value.getModifyDt();
        this.deleteDt = value.getDeleteDt();
        this.commitId = value.getCommitId();
        this.scopes = value.getScopes();
        this.action = value.getAction();
        this.remark = value.getRemark();
    }

    public WinPermEntry(
        Long id,
        LocalDateTime createDt,
        LocalDateTime modifyDt,
        LocalDateTime deleteDt,
        Long commitId,
        String scopes,
        String action,
        String remark
    ) {
        this.id = id;
        this.createDt = createDt;
        this.modifyDt = modifyDt;
        this.deleteDt = deleteDt;
        this.commitId = commitId;
        this.scopes = scopes;
        this.action = action;
        this.remark = remark;
    }

    /**
     * Getter for <code>win_perm_entry.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>win_perm_entry.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public void setIdIf(Long id, boolean bool) {
        if (bool) {
            this.id = id;
        }
    }

    public void setIdIf(Supplier<Long> id, boolean bool) {
        if (bool) {
            this.id = id.get();
        }
    }

    public void setIdIf(Long id, Predicate<Long> bool) {
        if (bool.test(id)) {
            this.id = id;
        }
    }

    public void setIdIf(Long id, Predicate<Long> bool, Supplier<Long>... ids) {
        if (bool.test(id)) {
            this.id = id;
            return;
        }
        for (Supplier<Long> supplier : ids) {
            id = supplier.get();
            if (bool.test(id)) {
                this.id = id;
                return;
            }
        }
    }

    public void setIdIfNot(Long id, Predicate<Long> bool) {
        if (!bool.test(id)) {
            this.id = id;
        }
    }

    public void setIdIfNot(Long id, Predicate<Long> bool, Supplier<Long>... ids) {
        if (!bool.test(id)) {
            this.id = id;
            return;
        }
        for (Supplier<Long> supplier : ids) {
            id = supplier.get();
            if (!bool.test(id)) {
                this.id = id;
                return;
            }
        }
    }

    public void setIdIf(UnaryOperator<Long> id) {
        this.id = id.apply(this.id);
    }


    /**
     * Getter for <code>win_perm_entry.create_dt</code>.
     */
    @Override
    public LocalDateTime getCreateDt() {
        return this.createDt;
    }

    /**
     * Setter for <code>win_perm_entry.create_dt</code>.
     */
    @Override
    public void setCreateDt(LocalDateTime createDt) {
        this.createDt = createDt;
    }

    public void setCreateDtIf(LocalDateTime createDt, boolean bool) {
        if (bool) {
            this.createDt = createDt;
        }
    }

    public void setCreateDtIf(Supplier<LocalDateTime> createDt, boolean bool) {
        if (bool) {
            this.createDt = createDt.get();
        }
    }

    public void setCreateDtIf(LocalDateTime createDt, Predicate<LocalDateTime> bool) {
        if (bool.test(createDt)) {
            this.createDt = createDt;
        }
    }

    public void setCreateDtIf(LocalDateTime createDt, Predicate<LocalDateTime> bool, Supplier<LocalDateTime>... createDts) {
        if (bool.test(createDt)) {
            this.createDt = createDt;
            return;
        }
        for (Supplier<LocalDateTime> supplier : createDts) {
            createDt = supplier.get();
            if (bool.test(createDt)) {
                this.createDt = createDt;
                return;
            }
        }
    }

    public void setCreateDtIfNot(LocalDateTime createDt, Predicate<LocalDateTime> bool) {
        if (!bool.test(createDt)) {
            this.createDt = createDt;
        }
    }

    public void setCreateDtIfNot(LocalDateTime createDt, Predicate<LocalDateTime> bool, Supplier<LocalDateTime>... createDts) {
        if (!bool.test(createDt)) {
            this.createDt = createDt;
            return;
        }
        for (Supplier<LocalDateTime> supplier : createDts) {
            createDt = supplier.get();
            if (!bool.test(createDt)) {
                this.createDt = createDt;
                return;
            }
        }
    }

    public void setCreateDtIf(UnaryOperator<LocalDateTime> createDt) {
        this.createDt = createDt.apply(this.createDt);
    }


    /**
     * Getter for <code>win_perm_entry.modify_dt</code>.
     */
    @Override
    public LocalDateTime getModifyDt() {
        return this.modifyDt;
    }

    /**
     * Setter for <code>win_perm_entry.modify_dt</code>.
     */
    @Override
    public void setModifyDt(LocalDateTime modifyDt) {
        this.modifyDt = modifyDt;
    }

    public void setModifyDtIf(LocalDateTime modifyDt, boolean bool) {
        if (bool) {
            this.modifyDt = modifyDt;
        }
    }

    public void setModifyDtIf(Supplier<LocalDateTime> modifyDt, boolean bool) {
        if (bool) {
            this.modifyDt = modifyDt.get();
        }
    }

    public void setModifyDtIf(LocalDateTime modifyDt, Predicate<LocalDateTime> bool) {
        if (bool.test(modifyDt)) {
            this.modifyDt = modifyDt;
        }
    }

    public void setModifyDtIf(LocalDateTime modifyDt, Predicate<LocalDateTime> bool, Supplier<LocalDateTime>... modifyDts) {
        if (bool.test(modifyDt)) {
            this.modifyDt = modifyDt;
            return;
        }
        for (Supplier<LocalDateTime> supplier : modifyDts) {
            modifyDt = supplier.get();
            if (bool.test(modifyDt)) {
                this.modifyDt = modifyDt;
                return;
            }
        }
    }

    public void setModifyDtIfNot(LocalDateTime modifyDt, Predicate<LocalDateTime> bool) {
        if (!bool.test(modifyDt)) {
            this.modifyDt = modifyDt;
        }
    }

    public void setModifyDtIfNot(LocalDateTime modifyDt, Predicate<LocalDateTime> bool, Supplier<LocalDateTime>... modifyDts) {
        if (!bool.test(modifyDt)) {
            this.modifyDt = modifyDt;
            return;
        }
        for (Supplier<LocalDateTime> supplier : modifyDts) {
            modifyDt = supplier.get();
            if (!bool.test(modifyDt)) {
                this.modifyDt = modifyDt;
                return;
            }
        }
    }

    public void setModifyDtIf(UnaryOperator<LocalDateTime> modifyDt) {
        this.modifyDt = modifyDt.apply(this.modifyDt);
    }


    /**
     * Getter for <code>win_perm_entry.delete_dt</code>.
     */
    @Override
    public LocalDateTime getDeleteDt() {
        return this.deleteDt;
    }

    /**
     * Setter for <code>win_perm_entry.delete_dt</code>.
     */
    @Override
    public void setDeleteDt(LocalDateTime deleteDt) {
        this.deleteDt = deleteDt;
    }

    public void setDeleteDtIf(LocalDateTime deleteDt, boolean bool) {
        if (bool) {
            this.deleteDt = deleteDt;
        }
    }

    public void setDeleteDtIf(Supplier<LocalDateTime> deleteDt, boolean bool) {
        if (bool) {
            this.deleteDt = deleteDt.get();
        }
    }

    public void setDeleteDtIf(LocalDateTime deleteDt, Predicate<LocalDateTime> bool) {
        if (bool.test(deleteDt)) {
            this.deleteDt = deleteDt;
        }
    }

    public void setDeleteDtIf(LocalDateTime deleteDt, Predicate<LocalDateTime> bool, Supplier<LocalDateTime>... deleteDts) {
        if (bool.test(deleteDt)) {
            this.deleteDt = deleteDt;
            return;
        }
        for (Supplier<LocalDateTime> supplier : deleteDts) {
            deleteDt = supplier.get();
            if (bool.test(deleteDt)) {
                this.deleteDt = deleteDt;
                return;
            }
        }
    }

    public void setDeleteDtIfNot(LocalDateTime deleteDt, Predicate<LocalDateTime> bool) {
        if (!bool.test(deleteDt)) {
            this.deleteDt = deleteDt;
        }
    }

    public void setDeleteDtIfNot(LocalDateTime deleteDt, Predicate<LocalDateTime> bool, Supplier<LocalDateTime>... deleteDts) {
        if (!bool.test(deleteDt)) {
            this.deleteDt = deleteDt;
            return;
        }
        for (Supplier<LocalDateTime> supplier : deleteDts) {
            deleteDt = supplier.get();
            if (!bool.test(deleteDt)) {
                this.deleteDt = deleteDt;
                return;
            }
        }
    }

    public void setDeleteDtIf(UnaryOperator<LocalDateTime> deleteDt) {
        this.deleteDt = deleteDt.apply(this.deleteDt);
    }


    /**
     * Getter for <code>win_perm_entry.commit_id</code>.
     */
    @Override
    public Long getCommitId() {
        return this.commitId;
    }

    /**
     * Setter for <code>win_perm_entry.commit_id</code>.
     */
    @Override
    public void setCommitId(Long commitId) {
        this.commitId = commitId;
    }

    public void setCommitIdIf(Long commitId, boolean bool) {
        if (bool) {
            this.commitId = commitId;
        }
    }

    public void setCommitIdIf(Supplier<Long> commitId, boolean bool) {
        if (bool) {
            this.commitId = commitId.get();
        }
    }

    public void setCommitIdIf(Long commitId, Predicate<Long> bool) {
        if (bool.test(commitId)) {
            this.commitId = commitId;
        }
    }

    public void setCommitIdIf(Long commitId, Predicate<Long> bool, Supplier<Long>... commitIds) {
        if (bool.test(commitId)) {
            this.commitId = commitId;
            return;
        }
        for (Supplier<Long> supplier : commitIds) {
            commitId = supplier.get();
            if (bool.test(commitId)) {
                this.commitId = commitId;
                return;
            }
        }
    }

    public void setCommitIdIfNot(Long commitId, Predicate<Long> bool) {
        if (!bool.test(commitId)) {
            this.commitId = commitId;
        }
    }

    public void setCommitIdIfNot(Long commitId, Predicate<Long> bool, Supplier<Long>... commitIds) {
        if (!bool.test(commitId)) {
            this.commitId = commitId;
            return;
        }
        for (Supplier<Long> supplier : commitIds) {
            commitId = supplier.get();
            if (!bool.test(commitId)) {
                this.commitId = commitId;
                return;
            }
        }
    }

    public void setCommitIdIf(UnaryOperator<Long> commitId) {
        this.commitId = commitId.apply(this.commitId);
    }


    /**
     * Getter for <code>win_perm_entry.scopes</code>.
     */
    @Override
    public String getScopes() {
        return this.scopes;
    }

    /**
     * Setter for <code>win_perm_entry.scopes</code>.
     */
    @Override
    public void setScopes(String scopes) {
        this.scopes = scopes;
    }

    public void setScopesIf(String scopes, boolean bool) {
        if (bool) {
            this.scopes = scopes;
        }
    }

    public void setScopesIf(Supplier<String> scopes, boolean bool) {
        if (bool) {
            this.scopes = scopes.get();
        }
    }

    public void setScopesIf(String scopes, Predicate<String> bool) {
        if (bool.test(scopes)) {
            this.scopes = scopes;
        }
    }

    public void setScopesIf(String scopes, Predicate<String> bool, Supplier<String>... scopess) {
        if (bool.test(scopes)) {
            this.scopes = scopes;
            return;
        }
        for (Supplier<String> supplier : scopess) {
            scopes = supplier.get();
            if (bool.test(scopes)) {
                this.scopes = scopes;
                return;
            }
        }
    }

    public void setScopesIfNot(String scopes, Predicate<String> bool) {
        if (!bool.test(scopes)) {
            this.scopes = scopes;
        }
    }

    public void setScopesIfNot(String scopes, Predicate<String> bool, Supplier<String>... scopess) {
        if (!bool.test(scopes)) {
            this.scopes = scopes;
            return;
        }
        for (Supplier<String> supplier : scopess) {
            scopes = supplier.get();
            if (!bool.test(scopes)) {
                this.scopes = scopes;
                return;
            }
        }
    }

    public void setScopesIf(UnaryOperator<String> scopes) {
        this.scopes = scopes.apply(this.scopes);
    }


    /**
     * Getter for <code>win_perm_entry.action</code>.
     */
    @Override
    public String getAction() {
        return this.action;
    }

    /**
     * Setter for <code>win_perm_entry.action</code>.
     */
    @Override
    public void setAction(String action) {
        this.action = action;
    }

    public void setActionIf(String action, boolean bool) {
        if (bool) {
            this.action = action;
        }
    }

    public void setActionIf(Supplier<String> action, boolean bool) {
        if (bool) {
            this.action = action.get();
        }
    }

    public void setActionIf(String action, Predicate<String> bool) {
        if (bool.test(action)) {
            this.action = action;
        }
    }

    public void setActionIf(String action, Predicate<String> bool, Supplier<String>... actions) {
        if (bool.test(action)) {
            this.action = action;
            return;
        }
        for (Supplier<String> supplier : actions) {
            action = supplier.get();
            if (bool.test(action)) {
                this.action = action;
                return;
            }
        }
    }

    public void setActionIfNot(String action, Predicate<String> bool) {
        if (!bool.test(action)) {
            this.action = action;
        }
    }

    public void setActionIfNot(String action, Predicate<String> bool, Supplier<String>... actions) {
        if (!bool.test(action)) {
            this.action = action;
            return;
        }
        for (Supplier<String> supplier : actions) {
            action = supplier.get();
            if (!bool.test(action)) {
                this.action = action;
                return;
            }
        }
    }

    public void setActionIf(UnaryOperator<String> action) {
        this.action = action.apply(this.action);
    }


    /**
     * Getter for <code>win_perm_entry.remark</code>.
     */
    @Override
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>win_perm_entry.remark</code>.
     */
    @Override
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setRemarkIf(String remark, boolean bool) {
        if (bool) {
            this.remark = remark;
        }
    }

    public void setRemarkIf(Supplier<String> remark, boolean bool) {
        if (bool) {
            this.remark = remark.get();
        }
    }

    public void setRemarkIf(String remark, Predicate<String> bool) {
        if (bool.test(remark)) {
            this.remark = remark;
        }
    }

    public void setRemarkIf(String remark, Predicate<String> bool, Supplier<String>... remarks) {
        if (bool.test(remark)) {
            this.remark = remark;
            return;
        }
        for (Supplier<String> supplier : remarks) {
            remark = supplier.get();
            if (bool.test(remark)) {
                this.remark = remark;
                return;
            }
        }
    }

    public void setRemarkIfNot(String remark, Predicate<String> bool) {
        if (!bool.test(remark)) {
            this.remark = remark;
        }
    }

    public void setRemarkIfNot(String remark, Predicate<String> bool, Supplier<String>... remarks) {
        if (!bool.test(remark)) {
            this.remark = remark;
            return;
        }
        for (Supplier<String> supplier : remarks) {
            remark = supplier.get();
            if (!bool.test(remark)) {
                this.remark = remark;
                return;
            }
        }
    }

    public void setRemarkIf(UnaryOperator<String> remark) {
        this.remark = remark.apply(this.remark);
    }


    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WinPermEntry other = (WinPermEntry) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createDt == null) {
            if (other.createDt != null)
                return false;
        }
        else if (!this.createDt.equals(other.createDt))
            return false;
        if (this.modifyDt == null) {
            if (other.modifyDt != null)
                return false;
        }
        else if (!this.modifyDt.equals(other.modifyDt))
            return false;
        if (this.deleteDt == null) {
            if (other.deleteDt != null)
                return false;
        }
        else if (!this.deleteDt.equals(other.deleteDt))
            return false;
        if (this.commitId == null) {
            if (other.commitId != null)
                return false;
        }
        else if (!this.commitId.equals(other.commitId))
            return false;
        if (this.scopes == null) {
            if (other.scopes != null)
                return false;
        }
        else if (!this.scopes.equals(other.scopes))
            return false;
        if (this.action == null) {
            if (other.action != null)
                return false;
        }
        else if (!this.action.equals(other.action))
            return false;
        if (this.remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!this.remark.equals(other.remark))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createDt == null) ? 0 : this.createDt.hashCode());
        result = prime * result + ((this.modifyDt == null) ? 0 : this.modifyDt.hashCode());
        result = prime * result + ((this.deleteDt == null) ? 0 : this.deleteDt.hashCode());
        result = prime * result + ((this.commitId == null) ? 0 : this.commitId.hashCode());
        result = prime * result + ((this.scopes == null) ? 0 : this.scopes.hashCode());
        result = prime * result + ((this.action == null) ? 0 : this.action.hashCode());
        result = prime * result + ((this.remark == null) ? 0 : this.remark.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WinPermEntry (");

        sb.append(id);
        sb.append(", ").append(createDt);
        sb.append(", ").append(modifyDt);
        sb.append(", ").append(deleteDt);
        sb.append(", ").append(commitId);
        sb.append(", ").append(scopes);
        sb.append(", ").append(action);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWinPermEntry from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setModifyDt(from.getModifyDt());
        setDeleteDt(from.getDeleteDt());
        setCommitId(from.getCommitId());
        setScopes(from.getScopes());
        setAction(from.getAction());
        setRemark(from.getRemark());
    }

    @Override
    public <E extends IWinPermEntry> E into(E into) {
        into.from(this);
        return into;
    }
}
