/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.tiny.mail.database.autogen.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import pro.fessional.wings.tiny.mail.database.autogen.tables.WinMailSenderTable;
import pro.fessional.wings.tiny.mail.database.autogen.tables.interfaces.IWinMailSender;
import pro.fessional.wings.tiny.mail.database.autogen.tables.pojos.WinMailSender;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;


/**
 * The table <code>wings.win_mail_sender</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7",
        "schema version:2020102701"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WinMailSenderRecord extends UpdatableRecordImpl<WinMailSenderRecord> implements IWinMailSender {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>win_mail_sender.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>win_mail_sender.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>win_mail_sender.create_dt</code>.
     */
    @Override
    public void setCreateDt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>win_mail_sender.create_dt</code>.
     */
    @Override
    public LocalDateTime getCreateDt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>win_mail_sender.modify_dt</code>.
     */
    @Override
    public void setModifyDt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>win_mail_sender.modify_dt</code>.
     */
    @Override
    public LocalDateTime getModifyDt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>win_mail_sender.delete_dt</code>.
     */
    @Override
    public void setDeleteDt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>win_mail_sender.delete_dt</code>.
     */
    @Override
    public LocalDateTime getDeleteDt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>win_mail_sender.commit_id</code>.
     */
    @Override
    public void setCommitId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>win_mail_sender.commit_id</code>.
     */
    @Override
    public Long getCommitId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>win_mail_sender.mail_apps</code>.
     */
    @Override
    public void setMailApps(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_apps</code>.
     */
    @Override
    public String getMailApps() {
        return (String) get(5);
    }

    /**
     * Setter for <code>win_mail_sender.mail_runs</code>.
     */
    @Override
    public void setMailRuns(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_runs</code>.
     */
    @Override
    public String getMailRuns() {
        return (String) get(6);
    }

    /**
     * Setter for <code>win_mail_sender.mail_conf</code>.
     */
    @Override
    public void setMailConf(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_conf</code>.
     */
    @Override
    public String getMailConf() {
        return (String) get(7);
    }

    /**
     * Setter for <code>win_mail_sender.mail_from</code>.
     */
    @Override
    public void setMailFrom(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_from</code>.
     */
    @Override
    public String getMailFrom() {
        return (String) get(8);
    }

    /**
     * Setter for <code>win_mail_sender.mail_to</code>.
     */
    @Override
    public void setMailTo(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_to</code>.
     */
    @Override
    public String getMailTo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>win_mail_sender.mail_cc</code>.
     */
    @Override
    public void setMailCc(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_cc</code>.
     */
    @Override
    public String getMailCc() {
        return (String) get(10);
    }

    /**
     * Setter for <code>win_mail_sender.mail_bcc</code>.
     */
    @Override
    public void setMailBcc(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_bcc</code>.
     */
    @Override
    public String getMailBcc() {
        return (String) get(11);
    }

    /**
     * Setter for <code>win_mail_sender.mail_reply</code>.
     */
    @Override
    public void setMailReply(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_reply</code>.
     */
    @Override
    public String getMailReply() {
        return (String) get(12);
    }

    /**
     * Setter for <code>win_mail_sender.mail_subj</code>.
     */
    @Override
    public void setMailSubj(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_subj</code>.
     */
    @Override
    public String getMailSubj() {
        return (String) get(13);
    }

    /**
     * Setter for <code>win_mail_sender.mail_text</code>.
     */
    @Override
    public void setMailText(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_text</code>.
     */
    @Override
    public String getMailText() {
        return (String) get(14);
    }

    /**
     * Setter for <code>win_mail_sender.mail_html</code>.
     */
    @Override
    public void setMailHtml(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_html</code>.
     */
    @Override
    public Boolean getMailHtml() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>win_mail_sender.mail_file</code>.
     */
    @Override
    public void setMailFile(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_file</code>.
     */
    @Override
    public String getMailFile() {
        return (String) get(16);
    }

    /**
     * Setter for <code>win_mail_sender.mail_mark</code>.
     */
    @Override
    public void setMailMark(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_mark</code>.
     */
    @Override
    public String getMailMark() {
        return (String) get(17);
    }

    /**
     * Setter for <code>win_mail_sender.mail_date</code>.
     */
    @Override
    public void setMailDate(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>win_mail_sender.mail_date</code>.
     */
    @Override
    public LocalDateTime getMailDate() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>win_mail_sender.last_send</code>.
     */
    @Override
    public void setLastSend(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>win_mail_sender.last_send</code>.
     */
    @Override
    public LocalDateTime getLastSend() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>win_mail_sender.last_fail</code>.
     */
    @Override
    public void setLastFail(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>win_mail_sender.last_fail</code>.
     */
    @Override
    public String getLastFail() {
        return (String) get(20);
    }

    /**
     * Setter for <code>win_mail_sender.last_done</code>.
     */
    @Override
    public void setLastDone(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>win_mail_sender.last_done</code>.
     */
    @Override
    public LocalDateTime getLastDone() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>win_mail_sender.last_cost</code>.
     */
    @Override
    public void setLastCost(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>win_mail_sender.last_cost</code>.
     */
    @Override
    public Integer getLastCost() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>win_mail_sender.next_send</code>.
     */
    @Override
    public void setNextSend(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>win_mail_sender.next_send</code>.
     */
    @Override
    public LocalDateTime getNextSend() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>win_mail_sender.next_lock</code>.
     */
    @Override
    public void setNextLock(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>win_mail_sender.next_lock</code>.
     */
    @Override
    public Integer getNextLock() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>win_mail_sender.sum_send</code>.
     */
    @Override
    public void setSumSend(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>win_mail_sender.sum_send</code>.
     */
    @Override
    public Integer getSumSend() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>win_mail_sender.sum_fail</code>.
     */
    @Override
    public void setSumFail(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>win_mail_sender.sum_fail</code>.
     */
    @Override
    public Integer getSumFail() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>win_mail_sender.sum_done</code>.
     */
    @Override
    public void setSumDone(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>win_mail_sender.sum_done</code>.
     */
    @Override
    public Integer getSumDone() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>win_mail_sender.max_fail</code>.
     */
    @Override
    public void setMaxFail(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>win_mail_sender.max_fail</code>.
     */
    @Override
    public Integer getMaxFail() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>win_mail_sender.max_done</code>.
     */
    @Override
    public void setMaxDone(Integer value) {
        set(29, value);
    }

    /**
     * Getter for <code>win_mail_sender.max_done</code>.
     */
    @Override
    public Integer getMaxDone() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>win_mail_sender.ref_type</code>.
     */
    @Override
    public void setRefType(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>win_mail_sender.ref_type</code>.
     */
    @Override
    public Integer getRefType() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>win_mail_sender.ref_key1</code>.
     */
    @Override
    public void setRefKey1(Long value) {
        set(31, value);
    }

    /**
     * Getter for <code>win_mail_sender.ref_key1</code>.
     */
    @Override
    public Long getRefKey1() {
        return (Long) get(31);
    }

    /**
     * Setter for <code>win_mail_sender.ref_key2</code>.
     */
    @Override
    public void setRefKey2(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>win_mail_sender.ref_key2</code>.
     */
    @Override
    public String getRefKey2() {
        return (String) get(32);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWinMailSender from) {
        setId(from.getId());
        setCreateDt(from.getCreateDt());
        setModifyDt(from.getModifyDt());
        setDeleteDt(from.getDeleteDt());
        setCommitId(from.getCommitId());
        setMailApps(from.getMailApps());
        setMailRuns(from.getMailRuns());
        setMailConf(from.getMailConf());
        setMailFrom(from.getMailFrom());
        setMailTo(from.getMailTo());
        setMailCc(from.getMailCc());
        setMailBcc(from.getMailBcc());
        setMailReply(from.getMailReply());
        setMailSubj(from.getMailSubj());
        setMailText(from.getMailText());
        setMailHtml(from.getMailHtml());
        setMailFile(from.getMailFile());
        setMailMark(from.getMailMark());
        setMailDate(from.getMailDate());
        setLastSend(from.getLastSend());
        setLastFail(from.getLastFail());
        setLastDone(from.getLastDone());
        setLastCost(from.getLastCost());
        setNextSend(from.getNextSend());
        setNextLock(from.getNextLock());
        setSumSend(from.getSumSend());
        setSumFail(from.getSumFail());
        setSumDone(from.getSumDone());
        setMaxFail(from.getMaxFail());
        setMaxDone(from.getMaxDone());
        setRefType(from.getRefType());
        setRefKey1(from.getRefKey1());
        setRefKey2(from.getRefKey2());
    }

    @Override
    public <E extends IWinMailSender> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WinMailSenderRecord
     */
    public WinMailSenderRecord() {
        super(WinMailSenderTable.WinMailSender);
    }

    /**
     * Create a detached, initialised WinMailSenderRecord
     */
    public WinMailSenderRecord(Long id, LocalDateTime createDt, LocalDateTime modifyDt, LocalDateTime deleteDt, Long commitId, String mailApps, String mailRuns, String mailConf, String mailFrom, String mailTo, String mailCc, String mailBcc, String mailReply, String mailSubj, String mailText, Boolean mailHtml, String mailFile, String mailMark, LocalDateTime mailDate, LocalDateTime lastSend, String lastFail, LocalDateTime lastDone, Integer lastCost, LocalDateTime nextSend, Integer nextLock, Integer sumSend, Integer sumFail, Integer sumDone, Integer maxFail, Integer maxDone, Integer refType, Long refKey1, String refKey2) {
        super(WinMailSenderTable.WinMailSender);

        setId(id);
        setCreateDt(createDt);
        setModifyDt(modifyDt);
        setDeleteDt(deleteDt);
        setCommitId(commitId);
        setMailApps(mailApps);
        setMailRuns(mailRuns);
        setMailConf(mailConf);
        setMailFrom(mailFrom);
        setMailTo(mailTo);
        setMailCc(mailCc);
        setMailBcc(mailBcc);
        setMailReply(mailReply);
        setMailSubj(mailSubj);
        setMailText(mailText);
        setMailHtml(mailHtml);
        setMailFile(mailFile);
        setMailMark(mailMark);
        setMailDate(mailDate);
        setLastSend(lastSend);
        setLastFail(lastFail);
        setLastDone(lastDone);
        setLastCost(lastCost);
        setNextSend(nextSend);
        setNextLock(nextLock);
        setSumSend(sumSend);
        setSumFail(sumFail);
        setSumDone(sumDone);
        setMaxFail(maxFail);
        setMaxDone(maxDone);
        setRefType(refType);
        setRefKey1(refKey1);
        setRefKey2(refKey2);
    }

    /**
     * Create a detached, initialised WinMailSenderRecord
     */
    public WinMailSenderRecord(WinMailSender value) {
        super(WinMailSenderTable.WinMailSender);

        if (value != null) {
            setId(value.getId());
            setCreateDt(value.getCreateDt());
            setModifyDt(value.getModifyDt());
            setDeleteDt(value.getDeleteDt());
            setCommitId(value.getCommitId());
            setMailApps(value.getMailApps());
            setMailRuns(value.getMailRuns());
            setMailConf(value.getMailConf());
            setMailFrom(value.getMailFrom());
            setMailTo(value.getMailTo());
            setMailCc(value.getMailCc());
            setMailBcc(value.getMailBcc());
            setMailReply(value.getMailReply());
            setMailSubj(value.getMailSubj());
            setMailText(value.getMailText());
            setMailHtml(value.getMailHtml());
            setMailFile(value.getMailFile());
            setMailMark(value.getMailMark());
            setMailDate(value.getMailDate());
            setLastSend(value.getLastSend());
            setLastFail(value.getLastFail());
            setLastDone(value.getLastDone());
            setLastCost(value.getLastCost());
            setNextSend(value.getNextSend());
            setNextLock(value.getNextLock());
            setSumSend(value.getSumSend());
            setSumFail(value.getSumFail());
            setSumDone(value.getSumDone());
            setMaxFail(value.getMaxFail());
            setMaxDone(value.getMaxDone());
            setRefType(value.getRefType());
            setRefKey1(value.getRefKey1());
            setRefKey2(value.getRefKey2());
        }
    }
}
