CREATE TABLE `SYS_LIGHT_SEQUENCE`
(
  `SEQ_NAME` varchar(100) NOT NULL COMMENT '序列名',
  `BLOCK_ID` int(11)      NOT NULL DEFAULT 0 COMMENT '分块序号',
  `NEXT_VAL` bigint(20)   NOT NULL DEFAULT '1' COMMENT '下一个序号',
  `STEP_VAL` int(11)      NOT NULL DEFAULT '100' COMMENT '序列步长',
  `COMMENTS` varchar(200) NOT NULL COMMENT '注释说明',
  PRIMARY KEY (`SEQ_NAME`, `BLOCK_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='序号生成器';

CREATE TABLE `SYS_COMMIT_JOURNAL`
(
  `ID`         bigint(20)   NOT NULL COMMENT '主键',
  `CREATE_DT`  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日时',
  `EVENT_NAME` varchar(100) NOT NULL COMMENT '事件名称',
  `TARGET_KEY` varchar(200) NOT NULL DEFAULT '' COMMENT '目标数据特征',
  `LOGIN_INFO` text COMMENT '登陆信息，用户，终端等',
  `OTHER_INFO` text COMMENT '其他信息，业务侧自定义',
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='变更日志';

-- --

INSERT INTO `SYS_LIGHT_SEQUENCE` (`SEQ_NAME`, `BLOCK_ID`, `NEXT_VAL`, `STEP_VAL`, `COMMENTS`)
VALUES ('SYS_COMMIT_JOURNAL', 0, 1, 100, 'SYS_COMMIT_JOURNAL');

INSERT INTO `SYS_COMMIT_JOURNAL`(`ID`, `EVENT_NAME`)
VALUES (0, 'SYSTEM_MANUAL_INIT');
