CREATE TABLE `SYS_LIGHT_SEQUENCE`
(
  `SEQ_NAME` varchar(100) NOT NULL COMMENT '序列名',
  `BLOCK_ID` int(11)      NOT NULL DEFAULT 0 COMMENT '分块序号',
  `NEXT_VAL` bigint(20)   NOT NULL DEFAULT '1' COMMENT '下一个序号',
  `STEP_VAL` bigint(20)   NOT NULL DEFAULT '100' COMMENT '序列步长',
  `COMMENTS` varchar(200) NOT NULL COMMENT '注释说明',
  PRIMARY KEY (`SEQ_NAME`, `BLOCK_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='序号生成器';

CREATE TABLE `SYS_COMMIT_JOURNAL`
(
  `ID`         bigint(20)   NOT NULL COMMENT '主键',
  `CREATE_DT`  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日时',
  `EVENT_NAME` varchar(100) NOT NULL COMMENT '事件名称',
  `TARGET_KEY` varchar(200) NOT NULL DEFAULT '' COMMENT '目标数据特征',
  `LOGIN_INFO` text COMMENT '登陆信息，用户，终端等',
  `OTHER_INFO` text COMMENT '其他信息，业务侧自定义',
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='变更日志';

CREATE TABLE `SYS_SCHEMA_MANAGER`
(
  `TABLE_NAME` varchar(100) NOT NULL COMMENT '主表表名',
  `CREATE_DT`  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日时',
  `MODIFY_DT`  datetime     NOT NULL DEFAULT '1000-01-01' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日时',
  `COMMIT_ID`  bigint(20)   NOT NULL COMMENT '提交ID',
  `LOG_UPDATE` tinyint(1)   NOT NULL DEFAULT '1' COMMENT '保留被更新记录',
  `LOG_DELETE` tinyint(1)   NOT NULL DEFAULT '1' COMMENT '保留被删除记录',
  `SHARD_AUTO` int(11)      NOT NULL DEFAULT '1' COMMENT '自动水平分表数量，1为不分表。',
  PRIMARY KEY (`TABLE_NAME`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='表结构管理';

CREATE TABLE `SYS_SCHEMA_VERSION`
(
  `REVISION`  bigint(20) NOT NULL COMMENT '版本号+修订号',
  `CREATE_DT` datetime   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日时',
  `MODIFY_DT` datetime   NOT NULL DEFAULT '1000-01-01' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日时',
  `COMMIT_ID` bigint(20) NOT NULL COMMENT '提交ID',
  `EXEC_SQL`  text       NOT NULL COMMENT '升级脚本',
  `EXEC_MD5`  char(32)   NOT NULL DEFAULT '' COMMENT '升级指纹',
  `UNDO_SQL`  text       NOT NULL COMMENT '降级脚本',
  `UNDO_MD5`  char(32)   NOT NULL DEFAULT '' COMMENT '降级指纹',
  `APPLY_DT`  datetime   NOT NULL DEFAULT '1000-01-01' COMMENT '执行日时',
  PRIMARY KEY (`REVISION`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='表结构版本';

-- --

INSERT INTO `SYS_LIGHT_SEQUENCE` (`SEQ_NAME`, `BLOCK_ID`, `NEXT_VAL`, `STEP_VAL`, `COMMENTS`)
VALUES ('SYS_COMMIT_JOURNAL', 0, 1, 100, 'SYS_COMMIT_JOURNAL');

INSERT INTO `SYS_COMMIT_JOURNAL`(`ID`, `EVENT_NAME`)
VALUES (1, 'MANUAL_INIT');

INSERT INTO `SYS_SCHEMA_MANAGER`(`TABLE_NAME`, `COMMIT_ID`, `LOG_UPDATE`, `LOG_DELETE`)
VALUES ('SYS_SCALE_SEQUENCE', 1, 0, 1),
       ('SYS_COMMIT_JOURNAL', 1, 1, 1),
       ('SYS_SCHEMA_MANAGER', 1, 1, 1),
       ('SYS_SCHEMA_VERSION', 1, 1, 1);

INSERT INTO `SYS_SCHEMA_VERSION`(`REVISION`, `COMMIT_ID`, `EXEC_SQL`, `EXEC_MD5`, `UNDO_SQL`, `UNDO_MD5`, `APPLY_DT`)
VALUES (2019051201, 1, '', '', '', '', NOW());
