CREATE TABLE `TST_中文也分表`
(
  `ID`         bigint(20) NOT NULL COMMENT '主键',
  `CREATE_DT`  datetime   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日时',
  `MODIFY_DT`  datetime   NOT NULL DEFAULT '1000-01-01' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日时',
  `COMMIT_ID`  bigint(20) NOT NULL COMMENT '提交ID',
  `LOGIN_INFO` text COMMENT '登陆信息，用户，终端等',
  `OTHER_INFO` text COMMENT '其他信息，业务侧自定义',
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='变更日志';
