/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.oracle.database.autogen.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import pro.fessional.wings.oracle.database.autogen.tables.SysSchemaVersion;
import pro.fessional.wings.oracle.database.autogen.tables.records.SysSchemaVersionRecord;
import pro.fessional.wings.oracle.service.lightid.LightIdAware;


/**
 * The table <code>wings.SYS_SCHEMA_VERSION</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9",
        "schema version:2019051201"
    },
    date = "2019-06-03T13:01:45.550Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysSchemaVersionDao extends DAOImpl<SysSchemaVersionRecord, pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion, Long> implements LightIdAware {

    /**
     * Create a new SysSchemaVersionDao without any configuration
     */
    public SysSchemaVersionDao() {
        super(SysSchemaVersion.SYS_SCHEMA_VERSION, pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion.class);
    }

    /**
     * Create a new SysSchemaVersionDao with an attached configuration
     */
    @Autowired
    public SysSchemaVersionDao(Configuration configuration) {
        super(SysSchemaVersion.SYS_SCHEMA_VERSION, pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion object) {
        return object.getRevision();
    }

    /**
     * Fetch records that have <code>REVISION IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByRevision(Long... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.REVISION, values);
    }

    /**
     * Fetch a unique record that has <code>REVISION = value</code>
     */
    public pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion fetchOneByRevision(Long value) {
        return fetchOne(SysSchemaVersion.SYS_SCHEMA_VERSION.REVISION, value);
    }

    /**
     * Fetch records that have <code>CREATE_DT IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByCreateDt(LocalDateTime... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.CREATE_DT, values);
    }

    /**
     * Fetch records that have <code>MODIFY_DT IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByModifyDt(LocalDateTime... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.MODIFY_DT, values);
    }

    /**
     * Fetch records that have <code>COMMIT_ID IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByCommitId(Long... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.COMMIT_ID, values);
    }

    /**
     * Fetch records that have <code>EXEC_SQL IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByExecSql(String... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.EXEC_SQL, values);
    }

    /**
     * Fetch records that have <code>EXEC_MD5 IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByExecMd5(String... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.EXEC_MD5, values);
    }

    /**
     * Fetch records that have <code>UNDO_SQL IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByUndoSql(String... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.UNDO_SQL, values);
    }

    /**
     * Fetch records that have <code>UNDO_MD5 IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByUndoMd5(String... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.UNDO_MD5, values);
    }

    /**
     * Fetch records that have <code>APPLY_DT IN (values)</code>
     */
    public List<pro.fessional.wings.oracle.database.autogen.tables.pojos.SysSchemaVersion> fetchByApplyDt(LocalDateTime... values) {
        return fetch(SysSchemaVersion.SYS_SCHEMA_VERSION.APPLY_DT, values);
    }
}
