/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.oracle.database.autogen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import pro.fessional.wings.oracle.service.lightid.LightIdAware;


/**
 * The table <code>wings.SYS_COMMIT_JOURNAL</code>.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9",
        "schema version:2019051201"
    },
    date = "2019-06-03T13:01:45.550Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "SYS_COMMIT_JOURNAL")
public interface ISysCommitJournal extends LightIdAware, Serializable {

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.ID</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.ID</code>.
     */
    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 19)
    @NotNull
    public Long getId();

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.CREATE_DT</code>.
     */
    public void setCreateDt(LocalDateTime value);

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.CREATE_DT</code>.
     */
    @Column(name = "CREATE_DT", nullable = false)
    public LocalDateTime getCreateDt();

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.EVENT_NAME</code>.
     */
    public void setEventName(String value);

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.EVENT_NAME</code>.
     */
    @Column(name = "EVENT_NAME", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getEventName();

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.TARGET_KEY</code>.
     */
    public void setTargetKey(String value);

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.TARGET_KEY</code>.
     */
    @Column(name = "TARGET_KEY", nullable = false, length = 200)
    @Size(max = 200)
    public String getTargetKey();

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.LOGIN_INFO</code>.
     */
    public void setLoginInfo(String value);

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.LOGIN_INFO</code>.
     */
    @Column(name = "LOGIN_INFO", length = 65535)
    @Size(max = 65535)
    public String getLoginInfo();

    /**
     * Setter for <code>SYS_COMMIT_JOURNAL.OTHER_INFO</code>.
     */
    public void setOtherInfo(String value);

    /**
     * Getter for <code>SYS_COMMIT_JOURNAL.OTHER_INFO</code>.
     */
    @Column(name = "OTHER_INFO", length = 65535)
    @Size(max = 65535)
    public String getOtherInfo();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISysCommitJournal
     */
    public void from(pro.fessional.wings.oracle.database.autogen.tables.interfaces.ISysCommitJournal from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISysCommitJournal
     */
    public <E extends pro.fessional.wings.oracle.database.autogen.tables.interfaces.ISysCommitJournal> E into(E into);
}
