/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables;


import org.jetbrains.annotations.NotNull;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function14;
import org.jooq.Name;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pro.fessional.wings.faceless.convention.EmptyValue;
import pro.fessional.wings.faceless.database.jooq.WingsJournalTable;
import pro.fessional.wings.faceless.service.journal.JournalService;
import pro.fessional.wings.faceless.service.lightid.LightIdAware;
import pro.fessional.wings.warlock.database.autogen.DefaultSchemaWarlock;
import pro.fessional.wings.warlock.database.autogen.tables.records.WinUserAuthnRecord;

import javax.annotation.processing.Generated;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;


/**
 * The table <code>wings.win_user_authn</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.14",
        "schema version:2020102501"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WinUserAuthnTable extends TableImpl<WinUserAuthnRecord> implements WingsJournalTable<WinUserAuthnTable>, LightIdAware {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>win_user_authn</code>
     */
    public static final WinUserAuthnTable WinUserAuthn = new WinUserAuthnTable();
    public static final WinUserAuthnTable asT2 = WinUserAuthn.as(pro.fessional.wings.faceless.database.jooq.WingsJooqEnv.uniqueAlias());

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WinUserAuthnRecord> getRecordType() {
        return WinUserAuthnRecord.class;
    }

    /**
     * The column <code>win_user_authn.id</code>.
     */
    public final TableField<WinUserAuthnRecord, Long> Id = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>win_user_authn.create_dt</code>.
     */
    public final TableField<WinUserAuthnRecord, LocalDateTime> CreateDt = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>win_user_authn.modify_dt</code>.
     */
    public final TableField<WinUserAuthnRecord, LocalDateTime> ModifyDt = createField(DSL.name("modify_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.inline("1000-01-01 00:00:00.000", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>win_user_authn.delete_dt</code>.
     */
    public final TableField<WinUserAuthnRecord, LocalDateTime> DeleteDt = createField(DSL.name("delete_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.inline("1000-01-01 00:00:00.000", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>win_user_authn.commit_id</code>.
     */
    public final TableField<WinUserAuthnRecord, Long> CommitId = createField(DSL.name("commit_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>win_user_authn.user_id</code>.
     */
    public final TableField<WinUserAuthnRecord, Long> UserId = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>win_user_authn.auth_type</code>.
     */
    public final TableField<WinUserAuthnRecord, String> AuthType = createField(DSL.name("auth_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>win_user_authn.username</code>.
     */
    public final TableField<WinUserAuthnRecord, String> Username = createField(DSL.name("username"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>win_user_authn.password</code>.
     */
    public final TableField<WinUserAuthnRecord, String> Password = createField(DSL.name("password"), SQLDataType.VARCHAR(200).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>win_user_authn.extra_para</code>.
     */
    public final TableField<WinUserAuthnRecord, String> ExtraPara = createField(DSL.name("extra_para"), SQLDataType.VARCHAR(3000).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>win_user_authn.extra_user</code>.
     */
    public final TableField<WinUserAuthnRecord, String> ExtraUser = createField(DSL.name("extra_user"), SQLDataType.VARCHAR(9000).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>win_user_authn.expired_dt</code>.
     */
    public final TableField<WinUserAuthnRecord, LocalDateTime> ExpiredDt = createField(DSL.name("expired_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.inline("1000-01-01 00:00:00.000", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>win_user_authn.failed_cnt</code>.
     */
    public final TableField<WinUserAuthnRecord, Integer> FailedCnt = createField(DSL.name("failed_cnt"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>win_user_authn.failed_max</code>.
     */
    public final TableField<WinUserAuthnRecord, Integer> FailedMax = createField(DSL.name("failed_max"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("5", SQLDataType.INTEGER)), this, "");

    private WinUserAuthnTable(Name alias, Table<WinUserAuthnRecord> aliased) {
        this(alias, aliased, null);
    }

    private WinUserAuthnTable(Name alias, Table<WinUserAuthnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>win_user_authn</code> table reference
     */
    public WinUserAuthnTable(String alias) {
        this(DSL.name(alias), WinUserAuthn);
    }

    /**
     * Create an aliased <code>win_user_authn</code> table reference
     */
    public WinUserAuthnTable(Name alias) {
        this(alias, WinUserAuthn);
    }

    /**
     * Create a <code>win_user_authn</code> table reference
     */
    public WinUserAuthnTable() {
        this(DSL.name("win_user_authn"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchemaWarlock.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<WinUserAuthnRecord> getPrimaryKey() {
        return Internal.createUniqueKey(WinUserAuthnTable.WinUserAuthn, DSL.name("KEY_win_user_authn_PRIMARY"), new TableField[] { WinUserAuthnTable.WinUserAuthn.Id }, true);
    }

    @Override
    public WinUserAuthnTable as(String alias) {
        return new WinUserAuthnTable(DSL.name(alias), this);
    }

    @Override
    public WinUserAuthnTable as(Name alias) {
        return new WinUserAuthnTable(alias, this);
    }

    @Override
    public WinUserAuthnTable as(Table<?> alias) {
        return new WinUserAuthnTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WinUserAuthnTable rename(String name) {
        return new WinUserAuthnTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WinUserAuthnTable rename(Name name) {
        return new WinUserAuthnTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WinUserAuthnTable rename(Table<?> name) {
        return new WinUserAuthnTable(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, LocalDateTime, LocalDateTime, LocalDateTime, Long, Long, String, String, String, String, String, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super Long, ? super LocalDateTime, ? super LocalDateTime, ? super LocalDateTime, ? super Long, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super Long, ? super LocalDateTime, ? super LocalDateTime, ? super LocalDateTime, ? super Long, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }

    /**
     * LightIdAware seqName
     */
    @Override
    @NotNull
    public String getSeqName() {
        return "win_user_authn";
    }
    

    /**
     * alias asT2
     */
    @Override
    @NotNull
    public WinUserAuthnTable getAliasTable() {
        return asT2;
    }
    

    /**
     * The colDel <code>delete_dt</code> condition
     */
    public final Condition DiedDataCondition = DeleteDt.gt(EmptyValue.DATE_TIME_AS_MAX);
    public final Condition LiveDataCondition = DeleteDt.lt(EmptyValue.DATE_TIME_AS_MAX);
    
    @Override
    @NotNull
    public Condition getOnlyDied() {
        return DiedDataCondition;
    }
    
    @Override
    @NotNull
    public Condition getOnlyLive() {
        return LiveDataCondition;
    }
    
    @Override
    @NotNull
    public Map<Field<?>, ?> markDelete(JournalService.Journal commit) {
        Map<org.jooq.Field<?>, Object> map = new HashMap<>();
        map.put(DeleteDt, commit.getCommitDt());
        map.put(CommitId, commit.getCommitId());
        return map;
    }
}
