# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 显示验证码
# 输出 code=null
GET http://localhost:8081/test/vcode.html

### 验证码
# 输出 captcha
GET http://localhost:8081/test/captcha.html

### 显示验证码
# 输出 code=123
GET http://localhost:8081/test/vcode.html

### 不带验证码查看
# 输出 bad captcha
GET http://localhost:8081/test/verify.html

### 带验证码查看
# 输出 /test/verify.html?vc=123
GET http://localhost:8081/test/verify.html?vc=123

### 全局产生验证码
# 输出 code=随机数
GET http://localhost:8081/test/vcode.html?ct=1

###