/*
 * This file is generated by jOOQ.
 */
package pro.fessional.wings.warlock.database.autogen.tables;


import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pro.fessional.wings.faceless.convention.EmptyValue;
import pro.fessional.wings.faceless.database.jooq.WingsAliasTable;
import pro.fessional.wings.warlock.database.autogen.DefaultSchema;
import pro.fessional.wings.warlock.database.autogen.tables.records.WinUserRoleMapRecord;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * The table <code>wings_warlock.win_user_role_map</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.4",
        "schema version:2020102402"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WinUserRoleMapTable extends TableImpl<WinUserRoleMapRecord> implements WingsAliasTable<WinUserRoleMapTable> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>win_user_role_map</code>
     */
    public static final WinUserRoleMapTable WinUserRoleMap = new WinUserRoleMapTable();
        public static final WinUserRoleMapTable asH4 = WinUserRoleMap.as("h4");

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WinUserRoleMapRecord> getRecordType() {
        return WinUserRoleMapRecord.class;
    }

    /**
     * The column <code>win_user_role_map.refer_user</code>.
     */
    public final TableField<WinUserRoleMapRecord, Long> ReferUser = createField(DSL.name("refer_user"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>win_user_role_map.grant_role</code>.
     */
    public final TableField<WinUserRoleMapRecord, Long> GrantRole = createField(DSL.name("grant_role"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>win_user_role_map.create_dt</code>.
     */
    public final TableField<WinUserRoleMapRecord, LocalDateTime> CreateDt = createField(DSL.name("create_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(3)", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>win_user_role_map.modify_dt</code>.
     */
    public final TableField<WinUserRoleMapRecord, LocalDateTime> ModifyDt = createField(DSL.name("modify_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.inline("1000-01-01 00:00:00.000", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>win_user_role_map.delete_dt</code>.
     */
    public final TableField<WinUserRoleMapRecord, LocalDateTime> DeleteDt = createField(DSL.name("delete_dt"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.inline("1000-01-01 00:00:00.000", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>win_user_role_map.commit_id</code>.
     */
    public final TableField<WinUserRoleMapRecord, Long> CommitId = createField(DSL.name("commit_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private WinUserRoleMapTable(Name alias, Table<WinUserRoleMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private WinUserRoleMapTable(Name alias, Table<WinUserRoleMapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>win_user_role_map</code> table reference
     */
    public WinUserRoleMapTable(String alias) {
        this(DSL.name(alias), WinUserRoleMap);
    }

    /**
     * Create an aliased <code>win_user_role_map</code> table reference
     */
    public WinUserRoleMapTable(Name alias) {
        this(alias, WinUserRoleMap);
    }

    /**
     * Create a <code>win_user_role_map</code> table reference
     */
    public WinUserRoleMapTable() {
        this(DSL.name("win_user_role_map"), null);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<WinUserRoleMapRecord> getPrimaryKey() {
        return Internal.createUniqueKey(WinUserRoleMapTable.WinUserRoleMap, DSL.name("KEY_win_user_role_map_PRIMARY"), new TableField[] { WinUserRoleMapTable.WinUserRoleMap.ReferUser, WinUserRoleMapTable.WinUserRoleMap.GrantRole }, true);
    }

    @Override
    public List<UniqueKey<WinUserRoleMapRecord>> getKeys() {
        return Arrays.<UniqueKey<WinUserRoleMapRecord>>asList(
              Internal.createUniqueKey(WinUserRoleMapTable.WinUserRoleMap, DSL.name("KEY_win_user_role_map_PRIMARY"), new TableField[] { WinUserRoleMapTable.WinUserRoleMap.ReferUser, WinUserRoleMapTable.WinUserRoleMap.GrantRole }, true)
        );
    }

    @Override
    public WinUserRoleMapTable as(String alias) {
        return new WinUserRoleMapTable(DSL.name(alias), this);
    }

    @Override
    public WinUserRoleMapTable as(Name alias) {
        return new WinUserRoleMapTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WinUserRoleMapTable rename(String name) {
        return new WinUserRoleMapTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WinUserRoleMapTable rename(Name name) {
        return new WinUserRoleMapTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, LocalDateTime, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * alias H4
     */
    @Override
    public WinUserRoleMapTable getAliasTable() {
            return asH4;
    }

    /**
     * The column <code>delete_dt</code> condition
     */
    public final Condition onlyDiedData = DeleteDt.gt(EmptyValue.DATE_TIME);
    public final Condition onlyLiveData = DeleteDt.eq(EmptyValue.DATE_TIME);
    @Override
    public Condition getOnlyDied() {
            return onlyDiedData;
    }
    @Override
    public Condition getOnlyLive() {
            return onlyLiveData;
    }
}
