CREATE DATABASE IF NOT EXISTS wings;
CREATE DATABASE IF NOT EXISTS wings_faceless;
CREATE DATABASE IF NOT EXISTS wings_shard_0;
CREATE DATABASE IF NOT EXISTS wings_shard_1;
CREATE DATABASE IF NOT EXISTS wings_warlock;
CREATE DATABASE IF NOT EXISTS wings_tiny;

GRANT ALL ON `wings%`.* TO 'trydofor'@'%';
FLUSH PRIVILEGES;
